// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3, arg4);
}

export function ConnectGuest(arg1, arg2) {
  return window['go']['main']['App']['ConnectGuest'](arg1, arg2);
}

export function Connected() {
  return window['go']['main']['App']['Connected']();
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function ExportIdentity() {
  return window['go']['main']['App']['ExportIdentity']();
}

export function GetAvatar(arg1) {
  return window['go']['main']['App']['GetAvatar'](arg1);
}

export function GetPermissions() {
  return window['go']['main']['App']['GetPermissions']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IdentityInfo() {
  return window['go']['main']['App']['IdentityInfo']();
}

export function IdentityUID() {
  return window['go']['main']['App']['IdentityUID']();
}

export function ImportIdentity() {
  return window['go']['main']['App']['ImportIdentity']();
}

export function JoinChannel(arg1) {
  return window['go']['main']['App']['JoinChannel'](arg1);
}

export function LogChat(arg1) {
  return window['go']['main']['App']['LogChat'](arg1);
}

export function OpenLogFolder() {
  return window['go']['main']['App']['OpenLogFolder']();
}

export function PickDownloadFolder() {
  return window['go']['main']['App']['PickDownloadFolder']();
}

export function RegenerateIdentity() {
  return window['go']['main']['App']['RegenerateIdentity']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SendChat(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendChat'](arg1, arg2, arg3);
}

export function SendICECandidate(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendICECandidate'](arg1, arg2, arg3);
}

export function SetAvatar(arg1) {
  return window['go']['main']['App']['SetAvatar'](arg1);
}

export function SetHotkeys(arg1, arg2) {
  return window['go']['main']['App']['SetHotkeys'](arg1, arg2);
}

export function SetMuted(arg1) {
  return window['go']['main']['App']['SetMuted'](arg1);
}

export function SetPTT(arg1) {
  return window['go']['main']['App']['SetPTT'](arg1);
}

export function SetScreenShare(arg1) {
  return window['go']['main']['App']['SetScreenShare'](arg1);
}

export function WebRTCAnswer(arg1) {
  return window['go']['main']['App']['WebRTCAnswer'](arg1);
}

export function WebRTCOffer(arg1) {
  return window['go']['main']['App']['WebRTCOffer'](arg1);
}

export function WhisperSet(arg1, arg2, arg3) {
  return window['go']['main']['App']['WhisperSet'](arg1, arg2, arg3);
}
