// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {netproto} from '../models';
import {main} from '../models';

export function Connect(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ConnectGuest(arg1:string,arg2:string):Promise<string>;

export function Connected():Promise<boolean>;

export function Disconnect():Promise<void>;

export function ExportIdentity():Promise<string>;

export function GetAvatar(arg1:string):Promise<netproto.AvatarData>;

export function GetClientInfo(arg1:string):Promise<netproto.ClientInfoResponse>;

export function GetPermissions():Promise<Array<netproto.PermissionEntry>>;

export function GetSettings():Promise<main.Settings>;

export function Greet(arg1:string):Promise<string>;

export function IdentityInfo():Promise<main.identityInfo>;

export function IdentityUID():Promise<string>;

export function ImportIdentity():Promise<string>;

export function JoinChannel(arg1:number):Promise<string>;

export function LogChat(arg1:string):Promise<void>;

export function OpenLogFolder():Promise<string>;

export function PickDownloadFolder():Promise<string>;

export function RegenerateIdentity():Promise<string>;

export function SaveSettings(arg1:main.Settings):Promise<string>;

export function SendChat(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SendICECandidate(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SetAvatar(arg1:string):Promise<string>;

export function SetHotkeys(arg1:string,arg2:string):Promise<string>;

export function SetMuted(arg1:boolean):Promise<void>;

export function SetPTT(arg1:boolean):Promise<void>;

export function SetScreenShare(arg1:boolean):Promise<string>;

export function WebRTCAnswer(arg1:string):Promise<void>;

export function WebRTCOffer(arg1:string):Promise<string>;

export function WhisperSet(arg1:Array<string>,arg2:Array<number>,arg3:boolean):Promise<string>;
