// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptServerRules(arg1) {
  return window['go']['main']['App']['AcceptServerRules'](arg1);
}

export function ApplyAndRestart() {
  return window['go']['main']['App']['ApplyAndRestart']();
}

export function ApplyHotkeyProfile(arg1) {
  return window['go']['main']['App']['ApplyHotkeyProfile'](arg1);
}

export function AuditLog(arg1, arg2) {
  return window['go']['main']['App']['AuditLog'](arg1, arg2);
}

export function BanList() {
  return window['go']['main']['App']['BanList']();
}

export function BanRemove(arg1) {
  return window['go']['main']['App']['BanRemove'](arg1);
}

export function CancelTransfer(arg1) {
  return window['go']['main']['App']['CancelTransfer'](arg1);
}

export function ChannelEdit(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['ChannelEdit'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function ChannelEditTree(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ChannelEditTree'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ChannelIconGet(arg1) {
  return window['go']['main']['App']['ChannelIconGet'](arg1);
}

export function ChannelIconSet(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChannelIconSet'](arg1, arg2, arg3);
}

export function ChatDeleteMessage(arg1) {
  return window['go']['main']['App']['ChatDeleteMessage'](arg1);
}

export function ChatEditMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ChatEditMessage'](arg1, arg2, arg3, arg4);
}

export function ChatExportHistory(arg1, arg2) {
  return window['go']['main']['App']['ChatExportHistory'](arg1, arg2);
}

export function ChatFilterGet() {
  return window['go']['main']['App']['ChatFilterGet']();
}

export function ChatFilterSet(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChatFilterSet'](arg1, arg2, arg3);
}

export function ChatHistory(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChatHistory'](arg1, arg2, arg3);
}

export function ChatPinMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChatPinMessage'](arg1, arg2, arg3);
}

export function ChatPins(arg1) {
  return window['go']['main']['App']['ChatPins'](arg1);
}

export function ChatReact(arg1, arg2) {
  return window['go']['main']['App']['ChatReact'](arg1, arg2);
}

export function ChatSearch(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChatSearch'](arg1, arg2, arg3);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClientID() {
  return window['go']['main']['App']['ClientID']();
}

export function ClientVersion() {
  return window['go']['main']['App']['ClientVersion']();
}

export function ClientVersionShort() {
  return window['go']['main']['App']['ClientVersionShort']();
}

export function CloseTab(arg1) {
  return window['go']['main']['App']['CloseTab'](arg1);
}

export function ComplaintClear(arg1, arg2) {
  return window['go']['main']['App']['ComplaintClear'](arg1, arg2);
}

export function ComplaintList() {
  return window['go']['main']['App']['ComplaintList']();
}

export function Connect(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3, arg4);
}

export function ConnectBookmarkTab(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ConnectBookmarkTab'](arg1, arg2, arg3, arg4, arg5);
}

export function ConnectGuest(arg1, arg2) {
  return window['go']['main']['App']['ConnectGuest'](arg1, arg2);
}

export function ConnectGuestBookmarkTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectGuestBookmarkTab'](arg1, arg2, arg3);
}

export function ConnectGuestTab(arg1, arg2) {
  return window['go']['main']['App']['ConnectGuestTab'](arg1, arg2);
}

export function ConnectTab(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConnectTab'](arg1, arg2, arg3, arg4);
}

export function Connected() {
  return window['go']['main']['App']['Connected']();
}

export function ConnectionSecurity() {
  return window['go']['main']['App']['ConnectionSecurity']();
}

export function CreateChannel(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) {
  return window['go']['main']['App']['CreateChannel'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
}

export function CreateIdentity(arg1) {
  return window['go']['main']['App']['CreateIdentity'](arg1);
}

export function DMExportHistory(arg1) {
  return window['go']['main']['App']['DMExportHistory'](arg1);
}

export function DMHistoryAppend(arg1, arg2, arg3) {
  return window['go']['main']['App']['DMHistoryAppend'](arg1, arg2, arg3);
}

export function DMHistoryClear(arg1) {
  return window['go']['main']['App']['DMHistoryClear'](arg1);
}

export function DMHistoryLoad(arg1) {
  return window['go']['main']['App']['DMHistoryLoad'](arg1);
}

export function DMHistoryPeers() {
  return window['go']['main']['App']['DMHistoryPeers']();
}

export function DMSearch(arg1, arg2, arg3) {
  return window['go']['main']['App']['DMSearch'](arg1, arg2, arg3);
}

export function DeleteChannel(arg1) {
  return window['go']['main']['App']['DeleteChannel'](arg1);
}

export function DeleteIdentity(arg1, arg2) {
  return window['go']['main']['App']['DeleteIdentity'](arg1, arg2);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function DownloadAndApply(arg1) {
  return window['go']['main']['App']['DownloadAndApply'](arg1);
}

export function DownloadChatAttachment(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadChatAttachment'](arg1, arg2, arg3);
}

export function DownloadFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2);
}

export function DownloadFileProgress(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['DownloadFileProgress'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DownloadPath(arg1) {
  return window['go']['main']['App']['DownloadPath'](arg1);
}

export function E2EEDiagnostics(arg1) {
  return window['go']['main']['App']['E2EEDiagnostics'](arg1);
}

export function EmojiDelete(arg1) {
  return window['go']['main']['App']['EmojiDelete'](arg1);
}

export function EmojiGet(arg1) {
  return window['go']['main']['App']['EmojiGet'](arg1);
}

export function EmojiList() {
  return window['go']['main']['App']['EmojiList']();
}

export function EmojiRename(arg1, arg2) {
  return window['go']['main']['App']['EmojiRename'](arg1, arg2);
}

export function EmojiUpload(arg1, arg2) {
  return window['go']['main']['App']['EmojiUpload'](arg1, arg2);
}

export function ExportChat(arg1, arg2) {
  return window['go']['main']['App']['ExportChat'](arg1, arg2);
}

export function ExportChatEncrypted(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportChatEncrypted'](arg1, arg2, arg3);
}

export function ExportIdentity(arg1) {
  return window['go']['main']['App']['ExportIdentity'](arg1);
}

export function ExportLogs() {
  return window['go']['main']['App']['ExportLogs']();
}

export function FileDelete(arg1, arg2, arg3) {
  return window['go']['main']['App']['FileDelete'](arg1, arg2, arg3);
}

export function FileLink(arg1, arg2, arg3) {
  return window['go']['main']['App']['FileLink'](arg1, arg2, arg3);
}

export function FileList(arg1, arg2) {
  return window['go']['main']['App']['FileList'](arg1, arg2);
}

export function FileRename(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['FileRename'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function FileVersions(arg1, arg2, arg3) {
  return window['go']['main']['App']['FileVersions'](arg1, arg2, arg3);
}

export function FlashWindow() {
  return window['go']['main']['App']['FlashWindow']();
}

export function GetAvatar(arg1) {
  return window['go']['main']['App']['GetAvatar'](arg1);
}

export function GetClientInfo(arg1) {
  return window['go']['main']['App']['GetClientInfo'](arg1);
}

export function GetICEServers() {
  return window['go']['main']['App']['GetICEServers']();
}

export function GetPermissions() {
  return window['go']['main']['App']['GetPermissions']();
}

export function GetServerConfig() {
  return window['go']['main']['App']['GetServerConfig']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function GroupAssign(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GroupAssign'](arg1, arg2, arg3, arg4, arg5);
}

export function GroupCreate(arg1, arg2, arg3) {
  return window['go']['main']['App']['GroupCreate'](arg1, arg2, arg3);
}

export function GroupDelete(arg1, arg2, arg3) {
  return window['go']['main']['App']['GroupDelete'](arg1, arg2, arg3);
}

export function GroupEdit(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GroupEdit'](arg1, arg2, arg3, arg4);
}

export function GroupIconGet(arg1) {
  return window['go']['main']['App']['GroupIconGet'](arg1);
}

export function GroupIconSet(arg1, arg2) {
  return window['go']['main']['App']['GroupIconSet'](arg1, arg2);
}

export function GroupList(arg1) {
  return window['go']['main']['App']['GroupList'](arg1);
}

export function GroupMembers(arg1, arg2, arg3) {
  return window['go']['main']['App']['GroupMembers'](arg1, arg2, arg3);
}

export function GroupRename(arg1, arg2, arg3) {
  return window['go']['main']['App']['GroupRename'](arg1, arg2, arg3);
}

export function GroupUnassign(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GroupUnassign'](arg1, arg2, arg3, arg4);
}

export function IdentityBackupPending() {
  return window['go']['main']['App']['IdentityBackupPending']();
}

export function IdentityInfo() {
  return window['go']['main']['App']['IdentityInfo']();
}

export function IdentityUID() {
  return window['go']['main']['App']['IdentityUID']();
}

export function ImportIdentity() {
  return window['go']['main']['App']['ImportIdentity']();
}

export function ImproveIdentityLevel(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImproveIdentityLevel'](arg1, arg2, arg3);
}

export function IsAdmin() {
  return window['go']['main']['App']['IsAdmin']();
}

export function JoinChannel(arg1) {
  return window['go']['main']['App']['JoinChannel'](arg1);
}

export function KickClient(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['KickClient'](arg1, arg2, arg3, arg4, arg5);
}

export function LastCrash() {
  return window['go']['main']['App']['LastCrash']();
}

export function ListIdentities() {
  return window['go']['main']['App']['ListIdentities']();
}

export function ListTabs() {
  return window['go']['main']['App']['ListTabs']();
}

export function LogChat(arg1) {
  return window['go']['main']['App']['LogChat'](arg1);
}

export function MOTD() {
  return window['go']['main']['App']['MOTD']();
}

export function MoveClient(arg1, arg2) {
  return window['go']['main']['App']['MoveClient'](arg1, arg2);
}

export function Notify(arg1, arg2) {
  return window['go']['main']['App']['Notify'](arg1, arg2);
}

export function OpenLogFolder() {
  return window['go']['main']['App']['OpenLogFolder']();
}

export function PermCopy(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['PermCopy'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function PermList(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PermList'](arg1, arg2, arg3, arg4);
}

export function PermSet(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['PermSet'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function PermTemplateApply(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PermTemplateApply'](arg1, arg2, arg3, arg4);
}

export function PermTrace(arg1, arg2, arg3) {
  return window['go']['main']['App']['PermTrace'](arg1, arg2, arg3);
}

export function PermUnset(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['PermUnset'](arg1, arg2, arg3, arg4, arg5);
}

export function PickDownloadFolder() {
  return window['go']['main']['App']['PickDownloadFolder']();
}

export function PickSavePath(arg1) {
  return window['go']['main']['App']['PickSavePath'](arg1);
}

export function PickUploadPaths() {
  return window['go']['main']['App']['PickUploadPaths']();
}

export function Poke(arg1, arg2) {
  return window['go']['main']['App']['Poke'](arg1, arg2);
}

export function RecordRecent(arg1, arg2) {
  return window['go']['main']['App']['RecordRecent'](arg1, arg2);
}

export function RegenerateIdentity() {
  return window['go']['main']['App']['RegenerateIdentity']();
}

export function RenameIdentity(arg1, arg2) {
  return window['go']['main']['App']['RenameIdentity'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SendChat(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendChat'](arg1, arg2, arg3);
}

export function SendChatDelivered(arg1, arg2) {
  return window['go']['main']['App']['SendChatDelivered'](arg1, arg2);
}

export function SendChatRead(arg1, arg2) {
  return window['go']['main']['App']['SendChatRead'](arg1, arg2);
}

export function SendChatReply(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendChatReply'](arg1, arg2, arg3, arg4);
}

export function SendICECandidate(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendICECandidate'](arg1, arg2, arg3);
}

export function SendTyping(arg1, arg2) {
  return window['go']['main']['App']['SendTyping'](arg1, arg2);
}

export function ServerBannerGet() {
  return window['go']['main']['App']['ServerBannerGet']();
}

export function ServerBannerSet(arg1) {
  return window['go']['main']['App']['ServerBannerSet'](arg1);
}

export function ServerFingerprint() {
  return window['go']['main']['App']['ServerFingerprint']();
}

export function ServerIconGet() {
  return window['go']['main']['App']['ServerIconGet']();
}

export function ServerIconSet(arg1) {
  return window['go']['main']['App']['ServerIconSet'](arg1);
}

export function ServerInfo() {
  return window['go']['main']['App']['ServerInfo']();
}

export function SetActiveTab(arg1) {
  return window['go']['main']['App']['SetActiveTab'](arg1);
}

export function SetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['SetAlwaysOnTop'](arg1);
}

export function SetAvatar(arg1) {
  return window['go']['main']['App']['SetAvatar'](arg1);
}

export function SetDebugFrames(arg1) {
  return window['go']['main']['App']['SetDebugFrames'](arg1);
}

export function SetHotkey(arg1, arg2) {
  return window['go']['main']['App']['SetHotkey'](arg1, arg2);
}

export function SetHotkeys(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetHotkeys'](arg1, arg2, arg3);
}

export function SetMuted(arg1) {
  return window['go']['main']['App']['SetMuted'](arg1);
}

export function SetPTT(arg1) {
  return window['go']['main']['App']['SetPTT'](arg1);
}

export function SetPrioritySpeaker(arg1) {
  return window['go']['main']['App']['SetPrioritySpeaker'](arg1);
}

export function SetScreenShare(arg1) {
  return window['go']['main']['App']['SetScreenShare'](arg1);
}

export function SetScreenShareQuality(arg1, arg2) {
  return window['go']['main']['App']['SetScreenShareQuality'](arg1, arg2);
}

export function SetServerConfig(arg1) {
  return window['go']['main']['App']['SetServerConfig'](arg1);
}

export function SetStatus(arg1, arg2) {
  return window['go']['main']['App']['SetStatus'](arg1, arg2);
}

export function SetVideoQuality(arg1) {
  return window['go']['main']['App']['SetVideoQuality'](arg1);
}

export function SetWindowOpacity(arg1) {
  return window['go']['main']['App']['SetWindowOpacity'](arg1);
}

export function SubscribeChannels(arg1, arg2) {
  return window['go']['main']['App']['SubscribeChannels'](arg1, arg2);
}

export function Subscriptions() {
  return window['go']['main']['App']['Subscriptions']();
}

export function SwitchIdentity(arg1) {
  return window['go']['main']['App']['SwitchIdentity'](arg1);
}

export function SystemCPUPercent() {
  return window['go']['main']['App']['SystemCPUPercent']();
}

export function TokenAdd(arg1, arg2, arg3) {
  return window['go']['main']['App']['TokenAdd'](arg1, arg2, arg3);
}

export function TokenDelete(arg1) {
  return window['go']['main']['App']['TokenDelete'](arg1);
}

export function TokenList() {
  return window['go']['main']['App']['TokenList']();
}

export function TokenUse(arg1) {
  return window['go']['main']['App']['TokenUse'](arg1);
}

export function TrayClearMentions() {
  return window['go']['main']['App']['TrayClearMentions']();
}

export function TrayMention() {
  return window['go']['main']['App']['TrayMention']();
}

export function TrustServerFingerprint(arg1, arg2) {
  return window['go']['main']['App']['TrustServerFingerprint'](arg1, arg2);
}

export function UploadChatAttachment(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadChatAttachment'](arg1, arg2, arg3);
}

export function UploadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2, arg3);
}

export function UploadFileProgress(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UploadFileProgress'](arg1, arg2, arg3, arg4, arg5);
}

export function UploadPathProgress(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UploadPathProgress'](arg1, arg2, arg3, arg4);
}

export function VerifyFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['VerifyFile'](arg1, arg2, arg3, arg4);
}

export function WebRTCAnswer(arg1) {
  return window['go']['main']['App']['WebRTCAnswer'](arg1);
}

export function WebRTCOffer(arg1, arg2) {
  return window['go']['main']['App']['WebRTCOffer'](arg1, arg2);
}

export function WhatsNew() {
  return window['go']['main']['App']['WhatsNew']();
}

export function WhisperSet(arg1, arg2, arg3) {
  return window['go']['main']['App']['WhisperSet'](arg1, arg2, arg3);
}
