// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: chat.proto

package voicxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatScope int32

const (
	ChatScope_CHAT_SCOPE_UNSPECIFIED ChatScope = 0
	ChatScope_CHAT_SCOPE_CHANNEL     ChatScope = 1
	ChatScope_CHAT_SCOPE_GLOBAL      ChatScope = 2
	ChatScope_CHAT_SCOPE_DIRECT      ChatScope = 3
)

// Enum value maps for ChatScope.
var (
	ChatScope_name = map[int32]string{
		0: "CHAT_SCOPE_UNSPECIFIED",
		1: "CHAT_SCOPE_CHANNEL",
		2: "CHAT_SCOPE_GLOBAL",
		3: "CHAT_SCOPE_DIRECT",
	}
	ChatScope_value = map[string]int32{
		"CHAT_SCOPE_UNSPECIFIED": 0,
		"CHAT_SCOPE_CHANNEL":     1,
		"CHAT_SCOPE_GLOBAL":      2,
		"CHAT_SCOPE_DIRECT":      3,
	}
)

func (x ChatScope) Enum() *ChatScope {
	p := new(ChatScope)
	*p = x
	return p
}

func (x ChatScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatScope) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_proto_enumTypes[0].Descriptor()
}

func (ChatScope) Type() protoreflect.EnumType {
	return &file_chat_proto_enumTypes[0]
}

func (x ChatScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatScope.Descriptor instead.
func (ChatScope) EnumDescriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

// ChatMessage is the canonical representation of a chat message.
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	RecipientId   string                 `protobuf:"bytes,4,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"` // empty for channel/global messages
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // unix millis
	Scope         ChatScope              `protobuf:"varint,7,opt,name=scope,proto3,enum=voicx.v1.ChatScope" json:"scope,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatMessage) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ChatMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ChatMessage) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ChatMessage) GetScope() ChatScope {
	if x != nil {
		return x.Scope
	}
	return ChatScope_CHAT_SCOPE_UNSPECIFIED
}

func (x *ChatMessage) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SendChannelChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendChannelChatRequest) Reset() {
	*x = SendChannelChatRequest{}
	mi := &file_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendChannelChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChannelChatRequest) ProtoMessage() {}

func (x *SendChannelChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChannelChatRequest.ProtoReflect.Descriptor instead.
func (*SendChannelChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1}
}

func (x *SendChannelChatRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *SendChannelChatRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendChannelChatRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SendGlobalChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendGlobalChatRequest) Reset() {
	*x = SendGlobalChatRequest{}
	mi := &file_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendGlobalChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGlobalChatRequest) ProtoMessage() {}

func (x *SendGlobalChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGlobalChatRequest.ProtoReflect.Descriptor instead.
func (*SendGlobalChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{2}
}

func (x *SendGlobalChatRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendGlobalChatRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SendDirectMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipientId   string                 `protobuf:"bytes,1,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendDirectMessageRequest) Reset() {
	*x = SendDirectMessageRequest{}
	mi := &file_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendDirectMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDirectMessageRequest) ProtoMessage() {}

func (x *SendDirectMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDirectMessageRequest.ProtoReflect.Descriptor instead.
func (*SendDirectMessageRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{3}
}

func (x *SendDirectMessageRequest) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

func (x *SendDirectMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendDirectMessageRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SendChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendChatResponse) Reset() {
	*x = SendChatResponse{}
	mi := &file_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChatResponse) ProtoMessage() {}

func (x *SendChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChatResponse.ProtoReflect.Descriptor instead.
func (*SendChatResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{4}
}

func (x *SendChatResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SendChatResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendChatResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FetchOfflineMessagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of messages to retrieve; 0 means server default.
	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// If set, only messages newer than this unix millis timestamp are returned.
	Since         int64 `protobuf:"varint,2,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchOfflineMessagesRequest) Reset() {
	*x = FetchOfflineMessagesRequest{}
	mi := &file_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchOfflineMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchOfflineMessagesRequest) ProtoMessage() {}

func (x *FetchOfflineMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchOfflineMessagesRequest.ProtoReflect.Descriptor instead.
func (*FetchOfflineMessagesRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{5}
}

func (x *FetchOfflineMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FetchOfflineMessagesRequest) GetSince() int64 {
	if x != nil {
		return x.Since
	}
	return 0
}

type FetchOfflineMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchOfflineMessagesResponse) Reset() {
	*x = FetchOfflineMessagesResponse{}
	mi := &file_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchOfflineMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchOfflineMessagesResponse) ProtoMessage() {}

func (x *FetchOfflineMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchOfflineMessagesResponse.ProtoReflect.Descriptor instead.
func (*FetchOfflineMessagesResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{6}
}

func (x *FetchOfflineMessagesResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *FetchOfflineMessagesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type AckOfflineMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageIds    []string               `protobuf:"bytes,1,rep,name=message_ids,json=messageIds,proto3" json:"message_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckOfflineMessagesRequest) Reset() {
	*x = AckOfflineMessagesRequest{}
	mi := &file_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckOfflineMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckOfflineMessagesRequest) ProtoMessage() {}

func (x *AckOfflineMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckOfflineMessagesRequest.ProtoReflect.Descriptor instead.
func (*AckOfflineMessagesRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{7}
}

func (x *AckOfflineMessagesRequest) GetMessageIds() []string {
	if x != nil {
		return x.MessageIds
	}
	return nil
}

type AckOfflineMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  int32                  `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	FailedIds     []string               `protobuf:"bytes,2,rep,name=failed_ids,json=failedIds,proto3" json:"failed_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckOfflineMessagesResponse) Reset() {
	*x = AckOfflineMessagesResponse{}
	mi := &file_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckOfflineMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckOfflineMessagesResponse) ProtoMessage() {}

func (x *AckOfflineMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckOfflineMessagesResponse.ProtoReflect.Descriptor instead.
func (*AckOfflineMessagesResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{8}
}

func (x *AckOfflineMessagesResponse) GetAcknowledged() int32 {
	if x != nil {
		return x.Acknowledged
	}
	return 0
}

func (x *AckOfflineMessagesResponse) GetFailedIds() []string {
	if x != nil {
		return x.FailedIds
	}
	return nil
}

var File_chat_proto protoreflect.FileDescriptor

const file_chat_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"chat.proto\x12\bvoicx.v1\"\xdd\x02\n" +
	"\vChatMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12!\n" +
	"\frecipient_id\x18\x04 \x01(\tR\vrecipientId\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12)\n" +
	"\x05scope\x18\a \x01(\x0e2\x13.voicx.v1.ChatScopeR\x05scope\x12?\n" +
	"\bmetadata\x18\b \x03(\v2#.voicx.v1.ChatMessage.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xda\x01\n" +
	"\x16SendChannelChatRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12J\n" +
	"\bmetadata\x18\x03 \x03(\v2..voicx.v1.SendChannelChatRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb9\x01\n" +
	"\x15SendGlobalChatRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12I\n" +
	"\bmetadata\x18\x02 \x03(\v2-.voicx.v1.SendGlobalChatRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe2\x01\n" +
	"\x18SendDirectMessageRequest\x12!\n" +
	"\frecipient_id\x18\x01 \x01(\tR\vrecipientId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12L\n" +
	"\bmetadata\x18\x03 \x03(\v20.voicx.v1.SendDirectMessageRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"c\n" +
	"\x10SendChatResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"I\n" +
	"\x1bFetchOfflineMessagesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x14\n" +
	"\x05since\x18\x02 \x01(\x03R\x05since\"l\n" +
	"\x1cFetchOfflineMessagesResponse\x121\n" +
	"\bmessages\x18\x01 \x03(\v2\x15.voicx.v1.ChatMessageR\bmessages\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"<\n" +
	"\x19AckOfflineMessagesRequest\x12\x1f\n" +
	"\vmessage_ids\x18\x01 \x03(\tR\n" +
	"messageIds\"_\n" +
	"\x1aAckOfflineMessagesResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\x05R\facknowledged\x12\x1d\n" +
	"\n" +
	"failed_ids\x18\x02 \x03(\tR\tfailedIds*m\n" +
	"\tChatScope\x12\x1a\n" +
	"\x16CHAT_SCOPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CHAT_SCOPE_CHANNEL\x10\x01\x12\x15\n" +
	"\x11CHAT_SCOPE_GLOBAL\x10\x02\x12\x15\n" +
	"\x11CHAT_SCOPE_DIRECT\x10\x032\xc3\x03\n" +
	"\x04Chat\x12O\n" +
	"\x0fSendChannelChat\x12 .voicx.v1.SendChannelChatRequest\x1a\x1a.voicx.v1.SendChatResponse\x12M\n" +
	"\x0eSendGlobalChat\x12\x1f.voicx.v1.SendGlobalChatRequest\x1a\x1a.voicx.v1.SendChatResponse\x12S\n" +
	"\x11SendDirectMessage\x12\".voicx.v1.SendDirectMessageRequest\x1a\x1a.voicx.v1.SendChatResponse\x12e\n" +
	"\x14FetchOfflineMessages\x12%.voicx.v1.FetchOfflineMessagesRequest\x1a&.voicx.v1.FetchOfflineMessagesResponse\x12_\n" +
	"\x12AckOfflineMessages\x12#.voicx.v1.AckOfflineMessagesRequest\x1a$.voicx.v1.AckOfflineMessagesResponseB\x12Z\x10voicx/v1;voicxv1b\x06proto3"

var (
	file_chat_proto_rawDescOnce sync.Once
	file_chat_proto_rawDescData []byte
)

func file_chat_proto_rawDescGZIP() []byte {
	file_chat_proto_rawDescOnce.Do(func() {
		file_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)))
	})
	return file_chat_proto_rawDescData
}

var file_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_chat_proto_goTypes = []any{
	(ChatScope)(0),                       // 0: voicx.v1.ChatScope
	(*ChatMessage)(nil),                  // 1: voicx.v1.ChatMessage
	(*SendChannelChatRequest)(nil),       // 2: voicx.v1.SendChannelChatRequest
	(*SendGlobalChatRequest)(nil),        // 3: voicx.v1.SendGlobalChatRequest
	(*SendDirectMessageRequest)(nil),     // 4: voicx.v1.SendDirectMessageRequest
	(*SendChatResponse)(nil),             // 5: voicx.v1.SendChatResponse
	(*FetchOfflineMessagesRequest)(nil),  // 6: voicx.v1.FetchOfflineMessagesRequest
	(*FetchOfflineMessagesResponse)(nil), // 7: voicx.v1.FetchOfflineMessagesResponse
	(*AckOfflineMessagesRequest)(nil),    // 8: voicx.v1.AckOfflineMessagesRequest
	(*AckOfflineMessagesResponse)(nil),   // 9: voicx.v1.AckOfflineMessagesResponse
	nil,                                  // 10: voicx.v1.ChatMessage.MetadataEntry
	nil,                                  // 11: voicx.v1.SendChannelChatRequest.MetadataEntry
	nil,                                  // 12: voicx.v1.SendGlobalChatRequest.MetadataEntry
	nil,                                  // 13: voicx.v1.SendDirectMessageRequest.MetadataEntry
}
var file_chat_proto_depIdxs = []int32{
	0,  // 0: voicx.v1.ChatMessage.scope:type_name -> voicx.v1.ChatScope
	10, // 1: voicx.v1.ChatMessage.metadata:type_name -> voicx.v1.ChatMessage.MetadataEntry
	11, // 2: voicx.v1.SendChannelChatRequest.metadata:type_name -> voicx.v1.SendChannelChatRequest.MetadataEntry
	12, // 3: voicx.v1.SendGlobalChatRequest.metadata:type_name -> voicx.v1.SendGlobalChatRequest.MetadataEntry
	13, // 4: voicx.v1.SendDirectMessageRequest.metadata:type_name -> voicx.v1.SendDirectMessageRequest.MetadataEntry
	1,  // 5: voicx.v1.FetchOfflineMessagesResponse.messages:type_name -> voicx.v1.ChatMessage
	2,  // 6: voicx.v1.Chat.SendChannelChat:input_type -> voicx.v1.SendChannelChatRequest
	3,  // 7: voicx.v1.Chat.SendGlobalChat:input_type -> voicx.v1.SendGlobalChatRequest
	4,  // 8: voicx.v1.Chat.SendDirectMessage:input_type -> voicx.v1.SendDirectMessageRequest
	6,  // 9: voicx.v1.Chat.FetchOfflineMessages:input_type -> voicx.v1.FetchOfflineMessagesRequest
	8,  // 10: voicx.v1.Chat.AckOfflineMessages:input_type -> voicx.v1.AckOfflineMessagesRequest
	5,  // 11: voicx.v1.Chat.SendChannelChat:output_type -> voicx.v1.SendChatResponse
	5,  // 12: voicx.v1.Chat.SendGlobalChat:output_type -> voicx.v1.SendChatResponse
	5,  // 13: voicx.v1.Chat.SendDirectMessage:output_type -> voicx.v1.SendChatResponse
	7,  // 14: voicx.v1.Chat.FetchOfflineMessages:output_type -> voicx.v1.FetchOfflineMessagesResponse
	9,  // 15: voicx.v1.Chat.AckOfflineMessages:output_type -> voicx.v1.AckOfflineMessagesResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_chat_proto_init() }
func file_chat_proto_init() {
	if File_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_proto_goTypes,
		DependencyIndexes: file_chat_proto_depIdxs,
		EnumInfos:         file_chat_proto_enumTypes,
		MessageInfos:      file_chat_proto_msgTypes,
	}.Build()
	File_chat_proto = out.File
	file_chat_proto_goTypes = nil
	file_chat_proto_depIdxs = nil
}
