// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: chat.proto

package voicxv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Chat_SendChannelChat_FullMethodName      = "/voicx.v1.Chat/SendChannelChat"
	Chat_SendGlobalChat_FullMethodName       = "/voicx.v1.Chat/SendGlobalChat"
	Chat_SendDirectMessage_FullMethodName    = "/voicx.v1.Chat/SendDirectMessage"
	Chat_FetchOfflineMessages_FullMethodName = "/voicx.v1.Chat/FetchOfflineMessages"
	Chat_AckOfflineMessages_FullMethodName   = "/voicx.v1.Chat/AckOfflineMessages"
)

// ChatClient is the client API for Chat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Chat service handles channel chat, global server chat, direct messages,
// and offline message spool requests.
type ChatClient interface {
	// SendChannelChat sends a message to a channel.
	SendChannelChat(ctx context.Context, in *SendChannelChatRequest, opts ...grpc.CallOption) (*SendChatResponse, error)
	// SendGlobalChat sends a message to the entire server.
	SendGlobalChat(ctx context.Context, in *SendGlobalChatRequest, opts ...grpc.CallOption) (*SendChatResponse, error)
	// SendDirectMessage sends a private message to a specific client.
	SendDirectMessage(ctx context.Context, in *SendDirectMessageRequest, opts ...grpc.CallOption) (*SendChatResponse, error)
	// FetchOfflineMessages retrieves messages spooled while the client was offline.
	FetchOfflineMessages(ctx context.Context, in *FetchOfflineMessagesRequest, opts ...grpc.CallOption) (*FetchOfflineMessagesResponse, error)
	// AckOfflineMessages acknowledges receipt of spooled messages so the server may delete them.
	AckOfflineMessages(ctx context.Context, in *AckOfflineMessagesRequest, opts ...grpc.CallOption) (*AckOfflineMessagesResponse, error)
}

type chatClient struct {
	cc grpc.ClientConnInterface
}

func NewChatClient(cc grpc.ClientConnInterface) ChatClient {
	return &chatClient{cc}
}

func (c *chatClient) SendChannelChat(ctx context.Context, in *SendChannelChatRequest, opts ...grpc.CallOption) (*SendChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendChatResponse)
	err := c.cc.Invoke(ctx, Chat_SendChannelChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) SendGlobalChat(ctx context.Context, in *SendGlobalChatRequest, opts ...grpc.CallOption) (*SendChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendChatResponse)
	err := c.cc.Invoke(ctx, Chat_SendGlobalChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) SendDirectMessage(ctx context.Context, in *SendDirectMessageRequest, opts ...grpc.CallOption) (*SendChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendChatResponse)
	err := c.cc.Invoke(ctx, Chat_SendDirectMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) FetchOfflineMessages(ctx context.Context, in *FetchOfflineMessagesRequest, opts ...grpc.CallOption) (*FetchOfflineMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchOfflineMessagesResponse)
	err := c.cc.Invoke(ctx, Chat_FetchOfflineMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) AckOfflineMessages(ctx context.Context, in *AckOfflineMessagesRequest, opts ...grpc.CallOption) (*AckOfflineMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckOfflineMessagesResponse)
	err := c.cc.Invoke(ctx, Chat_AckOfflineMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServer is the server API for Chat service.
// All implementations must embed UnimplementedChatServer
// for forward compatibility.
//
// Chat service handles channel chat, global server chat, direct messages,
// and offline message spool requests.
type ChatServer interface {
	// SendChannelChat sends a message to a channel.
	SendChannelChat(context.Context, *SendChannelChatRequest) (*SendChatResponse, error)
	// SendGlobalChat sends a message to the entire server.
	SendGlobalChat(context.Context, *SendGlobalChatRequest) (*SendChatResponse, error)
	// SendDirectMessage sends a private message to a specific client.
	SendDirectMessage(context.Context, *SendDirectMessageRequest) (*SendChatResponse, error)
	// FetchOfflineMessages retrieves messages spooled while the client was offline.
	FetchOfflineMessages(context.Context, *FetchOfflineMessagesRequest) (*FetchOfflineMessagesResponse, error)
	// AckOfflineMessages acknowledges receipt of spooled messages so the server may delete them.
	AckOfflineMessages(context.Context, *AckOfflineMessagesRequest) (*AckOfflineMessagesResponse, error)
	mustEmbedUnimplementedChatServer()
}

// UnimplementedChatServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatServer struct{}

func (UnimplementedChatServer) SendChannelChat(context.Context, *SendChannelChatRequest) (*SendChatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendChannelChat not implemented")
}
func (UnimplementedChatServer) SendGlobalChat(context.Context, *SendGlobalChatRequest) (*SendChatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendGlobalChat not implemented")
}
func (UnimplementedChatServer) SendDirectMessage(context.Context, *SendDirectMessageRequest) (*SendChatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendDirectMessage not implemented")
}
func (UnimplementedChatServer) FetchOfflineMessages(context.Context, *FetchOfflineMessagesRequest) (*FetchOfflineMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchOfflineMessages not implemented")
}
func (UnimplementedChatServer) AckOfflineMessages(context.Context, *AckOfflineMessagesRequest) (*AckOfflineMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AckOfflineMessages not implemented")
}
func (UnimplementedChatServer) mustEmbedUnimplementedChatServer() {}
func (UnimplementedChatServer) testEmbeddedByValue()              {}

// UnsafeChatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServer will
// result in compilation errors.
type UnsafeChatServer interface {
	mustEmbedUnimplementedChatServer()
}

func RegisterChatServer(s grpc.ServiceRegistrar, srv ChatServer) {
	// If the following call pancis, it indicates UnimplementedChatServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Chat_ServiceDesc, srv)
}

func _Chat_SendChannelChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendChannelChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).SendChannelChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_SendChannelChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).SendChannelChat(ctx, req.(*SendChannelChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_SendGlobalChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendGlobalChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).SendGlobalChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_SendGlobalChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).SendGlobalChat(ctx, req.(*SendGlobalChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_SendDirectMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendDirectMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).SendDirectMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_SendDirectMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).SendDirectMessage(ctx, req.(*SendDirectMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_FetchOfflineMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchOfflineMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).FetchOfflineMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_FetchOfflineMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).FetchOfflineMessages(ctx, req.(*FetchOfflineMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_AckOfflineMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckOfflineMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).AckOfflineMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_AckOfflineMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).AckOfflineMessages(ctx, req.(*AckOfflineMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Chat_ServiceDesc is the grpc.ServiceDesc for Chat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voicx.v1.Chat",
	HandlerType: (*ChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendChannelChat",
			Handler:    _Chat_SendChannelChat_Handler,
		},
		{
			MethodName: "SendGlobalChat",
			Handler:    _Chat_SendGlobalChat_Handler,
		},
		{
			MethodName: "SendDirectMessage",
			Handler:    _Chat_SendDirectMessage_Handler,
		},
		{
			MethodName: "FetchOfflineMessages",
			Handler:    _Chat_FetchOfflineMessages_Handler,
		},
		{
			MethodName: "AckOfflineMessages",
			Handler:    _Chat_AckOfflineMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chat.proto",
}
