// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: control.proto

package voicxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Permission int32

const (
	Permission_PERMISSION_UNSPECIFIED    Permission = 0
	Permission_PERMISSION_JOIN           Permission = 1
	Permission_PERMISSION_SPEAK          Permission = 2
	Permission_PERMISSION_VIDEO          Permission = 3
	Permission_PERMISSION_CHAT           Permission = 4
	Permission_PERMISSION_KICK           Permission = 5
	Permission_PERMISSION_BAN            Permission = 6
	Permission_PERMISSION_MOVE           Permission = 7
	Permission_PERMISSION_CREATE_CHANNEL Permission = 8
	Permission_PERMISSION_DELETE_CHANNEL Permission = 9
	Permission_PERMISSION_TRANSFER_FILE  Permission = 10
)

// Enum value maps for Permission.
var (
	Permission_name = map[int32]string{
		0:  "PERMISSION_UNSPECIFIED",
		1:  "PERMISSION_JOIN",
		2:  "PERMISSION_SPEAK",
		3:  "PERMISSION_VIDEO",
		4:  "PERMISSION_CHAT",
		5:  "PERMISSION_KICK",
		6:  "PERMISSION_BAN",
		7:  "PERMISSION_MOVE",
		8:  "PERMISSION_CREATE_CHANNEL",
		9:  "PERMISSION_DELETE_CHANNEL",
		10: "PERMISSION_TRANSFER_FILE",
	}
	Permission_value = map[string]int32{
		"PERMISSION_UNSPECIFIED":    0,
		"PERMISSION_JOIN":           1,
		"PERMISSION_SPEAK":          2,
		"PERMISSION_VIDEO":          3,
		"PERMISSION_CHAT":           4,
		"PERMISSION_KICK":           5,
		"PERMISSION_BAN":            6,
		"PERMISSION_MOVE":           7,
		"PERMISSION_CREATE_CHANNEL": 8,
		"PERMISSION_DELETE_CHANNEL": 9,
		"PERMISSION_TRANSFER_FILE":  10,
	}
)

func (x Permission) Enum() *Permission {
	p := new(Permission)
	*p = x
	return p
}

func (x Permission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Permission) Descriptor() protoreflect.EnumDescriptor {
	return file_control_proto_enumTypes[0].Descriptor()
}

func (Permission) Type() protoreflect.EnumType {
	return &file_control_proto_enumTypes[0]
}

func (x Permission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Permission.Descriptor instead.
func (Permission) EnumDescriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

type FileTransferDirection int32

const (
	FileTransferDirection_FILE_TRANSFER_DIRECTION_UNSPECIFIED FileTransferDirection = 0
	FileTransferDirection_FILE_TRANSFER_DIRECTION_UPLOAD      FileTransferDirection = 1
	FileTransferDirection_FILE_TRANSFER_DIRECTION_DOWNLOAD    FileTransferDirection = 2
)

// Enum value maps for FileTransferDirection.
var (
	FileTransferDirection_name = map[int32]string{
		0: "FILE_TRANSFER_DIRECTION_UNSPECIFIED",
		1: "FILE_TRANSFER_DIRECTION_UPLOAD",
		2: "FILE_TRANSFER_DIRECTION_DOWNLOAD",
	}
	FileTransferDirection_value = map[string]int32{
		"FILE_TRANSFER_DIRECTION_UNSPECIFIED": 0,
		"FILE_TRANSFER_DIRECTION_UPLOAD":      1,
		"FILE_TRANSFER_DIRECTION_DOWNLOAD":    2,
	}
)

func (x FileTransferDirection) Enum() *FileTransferDirection {
	p := new(FileTransferDirection)
	*p = x
	return p
}

func (x FileTransferDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileTransferDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_control_proto_enumTypes[1].Descriptor()
}

func (FileTransferDirection) Type() protoreflect.EnumType {
	return &file_control_proto_enumTypes[1]
}

func (x FileTransferDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileTransferDirection.Descriptor instead.
func (FileTransferDirection) EnumDescriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

type FileTransferStatus int32

const (
	FileTransferStatus_FILE_TRANSFER_STATUS_UNSPECIFIED FileTransferStatus = 0
	FileTransferStatus_FILE_TRANSFER_STATUS_PENDING     FileTransferStatus = 1
	FileTransferStatus_FILE_TRANSFER_STATUS_IN_PROGRESS FileTransferStatus = 2
	FileTransferStatus_FILE_TRANSFER_STATUS_COMPLETED   FileTransferStatus = 3
	FileTransferStatus_FILE_TRANSFER_STATUS_FAILED      FileTransferStatus = 4
	FileTransferStatus_FILE_TRANSFER_STATUS_CANCELED    FileTransferStatus = 5
)

// Enum value maps for FileTransferStatus.
var (
	FileTransferStatus_name = map[int32]string{
		0: "FILE_TRANSFER_STATUS_UNSPECIFIED",
		1: "FILE_TRANSFER_STATUS_PENDING",
		2: "FILE_TRANSFER_STATUS_IN_PROGRESS",
		3: "FILE_TRANSFER_STATUS_COMPLETED",
		4: "FILE_TRANSFER_STATUS_FAILED",
		5: "FILE_TRANSFER_STATUS_CANCELED",
	}
	FileTransferStatus_value = map[string]int32{
		"FILE_TRANSFER_STATUS_UNSPECIFIED": 0,
		"FILE_TRANSFER_STATUS_PENDING":     1,
		"FILE_TRANSFER_STATUS_IN_PROGRESS": 2,
		"FILE_TRANSFER_STATUS_COMPLETED":   3,
		"FILE_TRANSFER_STATUS_FAILED":      4,
		"FILE_TRANSFER_STATUS_CANCELED":    5,
	}
)

func (x FileTransferStatus) Enum() *FileTransferStatus {
	p := new(FileTransferStatus)
	*p = x
	return p
}

func (x FileTransferStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileTransferStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_control_proto_enumTypes[2].Descriptor()
}

func (FileTransferStatus) Type() protoreflect.EnumType {
	return &file_control_proto_enumTypes[2]
}

func (x FileTransferStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileTransferStatus.Descriptor instead.
func (FileTransferStatus) EnumDescriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

type AuthenticateRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Username string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// Optional pre-issued token (e.g. for reconnect).
	Token         string            `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	ClientVersion string            `protobuf:"bytes,4,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	Metadata      map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticateRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthenticateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AuthenticateRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthenticateRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *AuthenticateRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type AuthenticateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SessionToken  string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // unix millis
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthenticateResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *AuthenticateResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthenticateResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *AuthenticateResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *AuthenticateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Channel struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentId       string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	MaxClients     int32                  `protobuf:"varint,4,opt,name=max_clients,json=maxClients,proto3" json:"max_clients,omitempty"`
	Permanent      bool                   `protobuf:"varint,5,opt,name=permanent,proto3" json:"permanent,omitempty"`
	CurrentClients int32                  `protobuf:"varint,6,opt,name=current_clients,json=currentClients,proto3" json:"current_clients,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Channel) Reset() {
	*x = Channel{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Channel) ProtoMessage() {}

func (x *Channel) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Channel.ProtoReflect.Descriptor instead.
func (*Channel) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

func (x *Channel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Channel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Channel) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Channel) GetMaxClients() int32 {
	if x != nil {
		return x.MaxClients
	}
	return 0
}

func (x *Channel) GetPermanent() bool {
	if x != nil {
		return x.Permanent
	}
	return false
}

func (x *Channel) GetCurrentClients() int32 {
	if x != nil {
		return x.CurrentClients
	}
	return 0
}

func (x *Channel) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ParentId      string                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	MaxClients    int32                  `protobuf:"varint,3,opt,name=max_clients,json=maxClients,proto3" json:"max_clients,omitempty"`
	Permanent     bool                   `protobuf:"varint,4,opt,name=permanent,proto3" json:"permanent,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChannelRequest) Reset() {
	*x = CreateChannelRequest{}
	mi := &file_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChannelRequest) ProtoMessage() {}

func (x *CreateChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChannelRequest.ProtoReflect.Descriptor instead.
func (*CreateChannelRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

func (x *CreateChannelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateChannelRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *CreateChannelRequest) GetMaxClients() int32 {
	if x != nil {
		return x.MaxClients
	}
	return 0
}

func (x *CreateChannelRequest) GetPermanent() bool {
	if x != nil {
		return x.Permanent
	}
	return false
}

func (x *CreateChannelRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChannelResponse) Reset() {
	*x = CreateChannelResponse{}
	mi := &file_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChannelResponse) ProtoMessage() {}

func (x *CreateChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChannelResponse.ProtoReflect.Descriptor instead.
func (*CreateChannelResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{4}
}

func (x *CreateChannelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateChannelResponse) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *CreateChannelResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChannelRequest) Reset() {
	*x = DeleteChannelRequest{}
	mi := &file_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChannelRequest) ProtoMessage() {}

func (x *DeleteChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChannelRequest.ProtoReflect.Descriptor instead.
func (*DeleteChannelRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteChannelRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *DeleteChannelRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeleteChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChannelResponse) Reset() {
	*x = DeleteChannelResponse{}
	mi := &file_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChannelResponse) ProtoMessage() {}

func (x *DeleteChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChannelResponse.ProtoReflect.Descriptor instead.
func (*DeleteChannelResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteChannelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteChannelResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListChannelsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If set, only the subtree rooted at this channel is returned.
	RootChannelId string `protobuf:"bytes,1,opt,name=root_channel_id,json=rootChannelId,proto3" json:"root_channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelsRequest) Reset() {
	*x = ListChannelsRequest{}
	mi := &file_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelsRequest) ProtoMessage() {}

func (x *ListChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelsRequest.ProtoReflect.Descriptor instead.
func (*ListChannelsRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{7}
}

func (x *ListChannelsRequest) GetRootChannelId() string {
	if x != nil {
		return x.RootChannelId
	}
	return ""
}

type ListChannelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []*Channel             `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelsResponse) Reset() {
	*x = ListChannelsResponse{}
	mi := &file_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelsResponse) ProtoMessage() {}

func (x *ListChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelsResponse.ProtoReflect.Descriptor instead.
func (*ListChannelsResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{8}
}

func (x *ListChannelsResponse) GetChannels() []*Channel {
	if x != nil {
		return x.Channels
	}
	return nil
}

type QueryPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // empty means the authenticated caller
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPermissionsRequest) Reset() {
	*x = QueryPermissionsRequest{}
	mi := &file_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPermissionsRequest) ProtoMessage() {}

func (x *QueryPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPermissionsRequest.ProtoReflect.Descriptor instead.
func (*QueryPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{9}
}

func (x *QueryPermissionsRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *QueryPermissionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type QueryPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Granted       []Permission           `protobuf:"varint,1,rep,packed,name=granted,proto3,enum=voicx.v1.Permission" json:"granted,omitempty"`
	Denied        []Permission           `protobuf:"varint,2,rep,packed,name=denied,proto3,enum=voicx.v1.Permission" json:"denied,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,3,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPermissionsResponse) Reset() {
	*x = QueryPermissionsResponse{}
	mi := &file_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPermissionsResponse) ProtoMessage() {}

func (x *QueryPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPermissionsResponse.ProtoReflect.Descriptor instead.
func (*QueryPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{10}
}

func (x *QueryPermissionsResponse) GetGranted() []Permission {
	if x != nil {
		return x.Granted
	}
	return nil
}

func (x *QueryPermissionsResponse) GetDenied() []Permission {
	if x != nil {
		return x.Denied
	}
	return nil
}

func (x *QueryPermissionsResponse) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

type StartFileTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Direction     FileTransferDirection  `protobuf:"varint,4,opt,name=direction,proto3,enum=voicx.v1.FileTransferDirection" json:"direction,omitempty"`
	ContentType   string                 `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartFileTransferRequest) Reset() {
	*x = StartFileTransferRequest{}
	mi := &file_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartFileTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartFileTransferRequest) ProtoMessage() {}

func (x *StartFileTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartFileTransferRequest.ProtoReflect.Descriptor instead.
func (*StartFileTransferRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{11}
}

func (x *StartFileTransferRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *StartFileTransferRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *StartFileTransferRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *StartFileTransferRequest) GetDirection() FileTransferDirection {
	if x != nil {
		return x.Direction
	}
	return FileTransferDirection_FILE_TRANSFER_DIRECTION_UNSPECIFIED
}

func (x *StartFileTransferRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type StartFileTransferResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Success    bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TransferId string                 `protobuf:"bytes,2,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	// Endpoint where the client should send/receive file bytes (e.g. HTTP URL).
	Endpoint      string `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartFileTransferResponse) Reset() {
	*x = StartFileTransferResponse{}
	mi := &file_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartFileTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartFileTransferResponse) ProtoMessage() {}

func (x *StartFileTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartFileTransferResponse.ProtoReflect.Descriptor instead.
func (*StartFileTransferResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{12}
}

func (x *StartFileTransferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartFileTransferResponse) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *StartFileTransferResponse) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *StartFileTransferResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetFileTransferStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileTransferStatusRequest) Reset() {
	*x = GetFileTransferStatusRequest{}
	mi := &file_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileTransferStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileTransferStatusRequest) ProtoMessage() {}

func (x *GetFileTransferStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileTransferStatusRequest.ProtoReflect.Descriptor instead.
func (*GetFileTransferStatusRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{13}
}

func (x *GetFileTransferStatusRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

type GetFileTransferStatusResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TransferId       string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Status           FileTransferStatus     `protobuf:"varint,2,opt,name=status,proto3,enum=voicx.v1.FileTransferStatus" json:"status,omitempty"`
	BytesTransferred int64                  `protobuf:"varint,3,opt,name=bytes_transferred,json=bytesTransferred,proto3" json:"bytes_transferred,omitempty"`
	TotalBytes       int64                  `protobuf:"varint,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	Error            string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetFileTransferStatusResponse) Reset() {
	*x = GetFileTransferStatusResponse{}
	mi := &file_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileTransferStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileTransferStatusResponse) ProtoMessage() {}

func (x *GetFileTransferStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileTransferStatusResponse.ProtoReflect.Descriptor instead.
func (*GetFileTransferStatusResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{14}
}

func (x *GetFileTransferStatusResponse) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *GetFileTransferStatusResponse) GetStatus() FileTransferStatus {
	if x != nil {
		return x.Status
	}
	return FileTransferStatus_FILE_TRANSFER_STATUS_UNSPECIFIED
}

func (x *GetFileTransferStatusResponse) GetBytesTransferred() int64 {
	if x != nil {
		return x.BytesTransferred
	}
	return 0
}

func (x *GetFileTransferStatusResponse) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *GetFileTransferStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CancelFileTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelFileTransferRequest) Reset() {
	*x = CancelFileTransferRequest{}
	mi := &file_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelFileTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelFileTransferRequest) ProtoMessage() {}

func (x *CancelFileTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelFileTransferRequest.ProtoReflect.Descriptor instead.
func (*CancelFileTransferRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{15}
}

func (x *CancelFileTransferRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *CancelFileTransferRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelFileTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelFileTransferResponse) Reset() {
	*x = CancelFileTransferResponse{}
	mi := &file_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelFileTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelFileTransferResponse) ProtoMessage() {}

func (x *CancelFileTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelFileTransferResponse.ProtoReflect.Descriptor instead.
func (*CancelFileTransferResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{16}
}

func (x *CancelFileTransferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelFileTransferResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\bvoicx.v1\"\x90\x02\n" +
	"\x13AuthenticateRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12%\n" +
	"\x0eclient_version\x18\x04 \x01(\tR\rclientVersion\x12G\n" +
	"\bmetadata\x18\x05 \x03(\v2+.voicx.v1.AuthenticateRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc6\x01\n" +
	"\x14AuthenticateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\x03R\texpiresAt\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\xac\x02\n" +
	"\aChannel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\x12\x1f\n" +
	"\vmax_clients\x18\x04 \x01(\x05R\n" +
	"maxClients\x12\x1c\n" +
	"\tpermanent\x18\x05 \x01(\bR\tpermanent\x12'\n" +
	"\x0fcurrent_clients\x18\x06 \x01(\x05R\x0ecurrentClients\x12;\n" +
	"\bmetadata\x18\a \x03(\v2\x1f.voicx.v1.Channel.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8d\x02\n" +
	"\x14CreateChannelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\x12\x1f\n" +
	"\vmax_clients\x18\x03 \x01(\x05R\n" +
	"maxClients\x12\x1c\n" +
	"\tpermanent\x18\x04 \x01(\bR\tpermanent\x12H\n" +
	"\bmetadata\x18\x05 \x03(\v2,.voicx.v1.CreateChannelRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"f\n" +
	"\x15CreateChannelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"M\n" +
	"\x14DeleteChannelRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"G\n" +
	"\x15DeleteChannelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"=\n" +
	"\x13ListChannelsRequest\x12&\n" +
	"\x0froot_channel_id\x18\x01 \x01(\tR\rrootChannelId\"E\n" +
	"\x14ListChannelsResponse\x12-\n" +
	"\bchannels\x18\x01 \x03(\v2\x11.voicx.v1.ChannelR\bchannels\"Q\n" +
	"\x17QueryPermissionsRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x93\x01\n" +
	"\x18QueryPermissionsResponse\x12.\n" +
	"\agranted\x18\x01 \x03(\x0e2\x14.voicx.v1.PermissionR\agranted\x12,\n" +
	"\x06denied\x18\x02 \x03(\x0e2\x14.voicx.v1.PermissionR\x06denied\x12\x19\n" +
	"\bis_admin\x18\x03 \x01(\bR\aisAdmin\"\xd6\x01\n" +
	"\x18StartFileTransferRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12=\n" +
	"\tdirection\x18\x04 \x01(\x0e2\x1f.voicx.v1.FileTransferDirectionR\tdirection\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\"\x88\x01\n" +
	"\x19StartFileTransferResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vtransfer_id\x18\x02 \x01(\tR\n" +
	"transferId\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"?\n" +
	"\x1cGetFileTransferStatusRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\"\xda\x01\n" +
	"\x1dGetFileTransferStatusResponse\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x124\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1c.voicx.v1.FileTransferStatusR\x06status\x12+\n" +
	"\x11bytes_transferred\x18\x03 \x01(\x03R\x10bytesTransferred\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\x03R\n" +
	"totalBytes\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"T\n" +
	"\x19CancelFileTransferRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"L\n" +
	"\x1aCancelFileTransferResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error*\x98\x02\n" +
	"\n" +
	"Permission\x12\x1a\n" +
	"\x16PERMISSION_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPERMISSION_JOIN\x10\x01\x12\x14\n" +
	"\x10PERMISSION_SPEAK\x10\x02\x12\x14\n" +
	"\x10PERMISSION_VIDEO\x10\x03\x12\x13\n" +
	"\x0fPERMISSION_CHAT\x10\x04\x12\x13\n" +
	"\x0fPERMISSION_KICK\x10\x05\x12\x12\n" +
	"\x0ePERMISSION_BAN\x10\x06\x12\x13\n" +
	"\x0fPERMISSION_MOVE\x10\a\x12\x1d\n" +
	"\x19PERMISSION_CREATE_CHANNEL\x10\b\x12\x1d\n" +
	"\x19PERMISSION_DELETE_CHANNEL\x10\t\x12\x1c\n" +
	"\x18PERMISSION_TRANSFER_FILE\x10\n" +
	"*\x8a\x01\n" +
	"\x15FileTransferDirection\x12'\n" +
	"#FILE_TRANSFER_DIRECTION_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eFILE_TRANSFER_DIRECTION_UPLOAD\x10\x01\x12$\n" +
	" FILE_TRANSFER_DIRECTION_DOWNLOAD\x10\x02*\xea\x01\n" +
	"\x12FileTransferStatus\x12$\n" +
	" FILE_TRANSFER_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cFILE_TRANSFER_STATUS_PENDING\x10\x01\x12$\n" +
	" FILE_TRANSFER_STATUS_IN_PROGRESS\x10\x02\x12\"\n" +
	"\x1eFILE_TRANSFER_STATUS_COMPLETED\x10\x03\x12\x1f\n" +
	"\x1bFILE_TRANSFER_STATUS_FAILED\x10\x04\x12!\n" +
	"\x1dFILE_TRANSFER_STATUS_CANCELED\x10\x052\xcf\x05\n" +
	"\aControl\x12M\n" +
	"\fAuthenticate\x12\x1d.voicx.v1.AuthenticateRequest\x1a\x1e.voicx.v1.AuthenticateResponse\x12P\n" +
	"\rCreateChannel\x12\x1e.voicx.v1.CreateChannelRequest\x1a\x1f.voicx.v1.CreateChannelResponse\x12P\n" +
	"\rDeleteChannel\x12\x1e.voicx.v1.DeleteChannelRequest\x1a\x1f.voicx.v1.DeleteChannelResponse\x12M\n" +
	"\fListChannels\x12\x1d.voicx.v1.ListChannelsRequest\x1a\x1e.voicx.v1.ListChannelsResponse\x12Y\n" +
	"\x10QueryPermissions\x12!.voicx.v1.QueryPermissionsRequest\x1a\".voicx.v1.QueryPermissionsResponse\x12\\\n" +
	"\x11StartFileTransfer\x12\".voicx.v1.StartFileTransferRequest\x1a#.voicx.v1.StartFileTransferResponse\x12h\n" +
	"\x15GetFileTransferStatus\x12&.voicx.v1.GetFileTransferStatusRequest\x1a'.voicx.v1.GetFileTransferStatusResponse\x12_\n" +
	"\x12CancelFileTransfer\x12#.voicx.v1.CancelFileTransferRequest\x1a$.voicx.v1.CancelFileTransferResponseB\x12Z\x10voicx/v1;voicxv1b\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_control_proto_goTypes = []any{
	(Permission)(0),                       // 0: voicx.v1.Permission
	(FileTransferDirection)(0),            // 1: voicx.v1.FileTransferDirection
	(FileTransferStatus)(0),               // 2: voicx.v1.FileTransferStatus
	(*AuthenticateRequest)(nil),           // 3: voicx.v1.AuthenticateRequest
	(*AuthenticateResponse)(nil),          // 4: voicx.v1.AuthenticateResponse
	(*Channel)(nil),                       // 5: voicx.v1.Channel
	(*CreateChannelRequest)(nil),          // 6: voicx.v1.CreateChannelRequest
	(*CreateChannelResponse)(nil),         // 7: voicx.v1.CreateChannelResponse
	(*DeleteChannelRequest)(nil),          // 8: voicx.v1.DeleteChannelRequest
	(*DeleteChannelResponse)(nil),         // 9: voicx.v1.DeleteChannelResponse
	(*ListChannelsRequest)(nil),           // 10: voicx.v1.ListChannelsRequest
	(*ListChannelsResponse)(nil),          // 11: voicx.v1.ListChannelsResponse
	(*QueryPermissionsRequest)(nil),       // 12: voicx.v1.QueryPermissionsRequest
	(*QueryPermissionsResponse)(nil),      // 13: voicx.v1.QueryPermissionsResponse
	(*StartFileTransferRequest)(nil),      // 14: voicx.v1.StartFileTransferRequest
	(*StartFileTransferResponse)(nil),     // 15: voicx.v1.StartFileTransferResponse
	(*GetFileTransferStatusRequest)(nil),  // 16: voicx.v1.GetFileTransferStatusRequest
	(*GetFileTransferStatusResponse)(nil), // 17: voicx.v1.GetFileTransferStatusResponse
	(*CancelFileTransferRequest)(nil),     // 18: voicx.v1.CancelFileTransferRequest
	(*CancelFileTransferResponse)(nil),    // 19: voicx.v1.CancelFileTransferResponse
	nil,                                   // 20: voicx.v1.AuthenticateRequest.MetadataEntry
	nil,                                   // 21: voicx.v1.Channel.MetadataEntry
	nil,                                   // 22: voicx.v1.CreateChannelRequest.MetadataEntry
}
var file_control_proto_depIdxs = []int32{
	20, // 0: voicx.v1.AuthenticateRequest.metadata:type_name -> voicx.v1.AuthenticateRequest.MetadataEntry
	21, // 1: voicx.v1.Channel.metadata:type_name -> voicx.v1.Channel.MetadataEntry
	22, // 2: voicx.v1.CreateChannelRequest.metadata:type_name -> voicx.v1.CreateChannelRequest.MetadataEntry
	5,  // 3: voicx.v1.ListChannelsResponse.channels:type_name -> voicx.v1.Channel
	0,  // 4: voicx.v1.QueryPermissionsResponse.granted:type_name -> voicx.v1.Permission
	0,  // 5: voicx.v1.QueryPermissionsResponse.denied:type_name -> voicx.v1.Permission
	1,  // 6: voicx.v1.StartFileTransferRequest.direction:type_name -> voicx.v1.FileTransferDirection
	2,  // 7: voicx.v1.GetFileTransferStatusResponse.status:type_name -> voicx.v1.FileTransferStatus
	3,  // 8: voicx.v1.Control.Authenticate:input_type -> voicx.v1.AuthenticateRequest
	6,  // 9: voicx.v1.Control.CreateChannel:input_type -> voicx.v1.CreateChannelRequest
	8,  // 10: voicx.v1.Control.DeleteChannel:input_type -> voicx.v1.DeleteChannelRequest
	10, // 11: voicx.v1.Control.ListChannels:input_type -> voicx.v1.ListChannelsRequest
	12, // 12: voicx.v1.Control.QueryPermissions:input_type -> voicx.v1.QueryPermissionsRequest
	14, // 13: voicx.v1.Control.StartFileTransfer:input_type -> voicx.v1.StartFileTransferRequest
	16, // 14: voicx.v1.Control.GetFileTransferStatus:input_type -> voicx.v1.GetFileTransferStatusRequest
	18, // 15: voicx.v1.Control.CancelFileTransfer:input_type -> voicx.v1.CancelFileTransferRequest
	4,  // 16: voicx.v1.Control.Authenticate:output_type -> voicx.v1.AuthenticateResponse
	7,  // 17: voicx.v1.Control.CreateChannel:output_type -> voicx.v1.CreateChannelResponse
	9,  // 18: voicx.v1.Control.DeleteChannel:output_type -> voicx.v1.DeleteChannelResponse
	11, // 19: voicx.v1.Control.ListChannels:output_type -> voicx.v1.ListChannelsResponse
	13, // 20: voicx.v1.Control.QueryPermissions:output_type -> voicx.v1.QueryPermissionsResponse
	15, // 21: voicx.v1.Control.StartFileTransfer:output_type -> voicx.v1.StartFileTransferResponse
	17, // 22: voicx.v1.Control.GetFileTransferStatus:output_type -> voicx.v1.GetFileTransferStatusResponse
	19, // 23: voicx.v1.Control.CancelFileTransfer:output_type -> voicx.v1.CancelFileTransferResponse
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		EnumInfos:         file_control_proto_enumTypes,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
