// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: events.proto

package voicxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED     EventType = 0
	EventType_EVENT_TYPE_USER_JOINED     EventType = 1
	EventType_EVENT_TYPE_USER_LEFT       EventType = 2
	EventType_EVENT_TYPE_USER_SPEAKING   EventType = 3
	EventType_EVENT_TYPE_CHANNEL_CREATED EventType = 4
	EventType_EVENT_TYPE_CHANNEL_DELETED EventType = 5
	EventType_EVENT_TYPE_USER_MOVED      EventType = 6
	EventType_EVENT_TYPE_USER_KICKED     EventType = 7
	EventType_EVENT_TYPE_USER_BANNED     EventType = 8
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_USER_JOINED",
		2: "EVENT_TYPE_USER_LEFT",
		3: "EVENT_TYPE_USER_SPEAKING",
		4: "EVENT_TYPE_CHANNEL_CREATED",
		5: "EVENT_TYPE_CHANNEL_DELETED",
		6: "EVENT_TYPE_USER_MOVED",
		7: "EVENT_TYPE_USER_KICKED",
		8: "EVENT_TYPE_USER_BANNED",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":     0,
		"EVENT_TYPE_USER_JOINED":     1,
		"EVENT_TYPE_USER_LEFT":       2,
		"EVENT_TYPE_USER_SPEAKING":   3,
		"EVENT_TYPE_CHANNEL_CREATED": 4,
		"EVENT_TYPE_CHANNEL_DELETED": 5,
		"EVENT_TYPE_USER_MOVED":      6,
		"EVENT_TYPE_USER_KICKED":     7,
		"EVENT_TYPE_USER_BANNED":     8,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_events_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_events_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

type SubscribeEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filter of event types to receive; empty means all.
	EventTypes    []EventType `protobuf:"varint,1,rep,packed,name=event_types,json=eventTypes,proto3,enum=voicx.v1.EventType" json:"event_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeEventsRequest) Reset() {
	*x = SubscribeEventsRequest{}
	mi := &file_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventsRequest) ProtoMessage() {}

func (x *SubscribeEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeEventsRequest) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeEventsRequest) GetEventTypes() []EventType {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

// Event is the envelope for all server events. Exactly one payload field is set.
type Event struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type      EventType              `protobuf:"varint,2,opt,name=type,proto3,enum=voicx.v1.EventType" json:"type,omitempty"`
	Timestamp int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // unix millis
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_UserJoined
	//	*Event_UserLeft
	//	*Event_UserSpeaking
	//	*Event_ChannelCreated
	//	*Event_ChannelDeleted
	//	*Event_UserMoved
	//	*Event_UserKicked
	//	*Event_UserBanned
	Payload       isEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *Event) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetUserJoined() *UserJoinedEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_UserJoined); ok {
			return x.UserJoined
		}
	}
	return nil
}

func (x *Event) GetUserLeft() *UserLeftEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_UserLeft); ok {
			return x.UserLeft
		}
	}
	return nil
}

func (x *Event) GetUserSpeaking() *UserSpeakingEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_UserSpeaking); ok {
			return x.UserSpeaking
		}
	}
	return nil
}

func (x *Event) GetChannelCreated() *ChannelCreatedEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_ChannelCreated); ok {
			return x.ChannelCreated
		}
	}
	return nil
}

func (x *Event) GetChannelDeleted() *ChannelDeletedEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_ChannelDeleted); ok {
			return x.ChannelDeleted
		}
	}
	return nil
}

func (x *Event) GetUserMoved() *UserMovedEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_UserMoved); ok {
			return x.UserMoved
		}
	}
	return nil
}

func (x *Event) GetUserKicked() *UserKickedEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_UserKicked); ok {
			return x.UserKicked
		}
	}
	return nil
}

func (x *Event) GetUserBanned() *UserBannedEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_UserBanned); ok {
			return x.UserBanned
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_UserJoined struct {
	UserJoined *UserJoinedEvent `protobuf:"bytes,10,opt,name=user_joined,json=userJoined,proto3,oneof"`
}

type Event_UserLeft struct {
	UserLeft *UserLeftEvent `protobuf:"bytes,11,opt,name=user_left,json=userLeft,proto3,oneof"`
}

type Event_UserSpeaking struct {
	UserSpeaking *UserSpeakingEvent `protobuf:"bytes,12,opt,name=user_speaking,json=userSpeaking,proto3,oneof"`
}

type Event_ChannelCreated struct {
	ChannelCreated *ChannelCreatedEvent `protobuf:"bytes,13,opt,name=channel_created,json=channelCreated,proto3,oneof"`
}

type Event_ChannelDeleted struct {
	ChannelDeleted *ChannelDeletedEvent `protobuf:"bytes,14,opt,name=channel_deleted,json=channelDeleted,proto3,oneof"`
}

type Event_UserMoved struct {
	UserMoved *UserMovedEvent `protobuf:"bytes,15,opt,name=user_moved,json=userMoved,proto3,oneof"`
}

type Event_UserKicked struct {
	UserKicked *UserKickedEvent `protobuf:"bytes,16,opt,name=user_kicked,json=userKicked,proto3,oneof"`
}

type Event_UserBanned struct {
	UserBanned *UserBannedEvent `protobuf:"bytes,17,opt,name=user_banned,json=userBanned,proto3,oneof"`
}

func (*Event_UserJoined) isEvent_Payload() {}

func (*Event_UserLeft) isEvent_Payload() {}

func (*Event_UserSpeaking) isEvent_Payload() {}

func (*Event_ChannelCreated) isEvent_Payload() {}

func (*Event_ChannelDeleted) isEvent_Payload() {}

func (*Event_UserMoved) isEvent_Payload() {}

func (*Event_UserKicked) isEvent_Payload() {}

func (*Event_UserBanned) isEvent_Payload() {}

type UserJoinedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserJoinedEvent) Reset() {
	*x = UserJoinedEvent{}
	mi := &file_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserJoinedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserJoinedEvent) ProtoMessage() {}

func (x *UserJoinedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserJoinedEvent.ProtoReflect.Descriptor instead.
func (*UserJoinedEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{2}
}

func (x *UserJoinedEvent) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *UserJoinedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserJoinedEvent) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type UserLeftEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLeftEvent) Reset() {
	*x = UserLeftEvent{}
	mi := &file_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLeftEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLeftEvent) ProtoMessage() {}

func (x *UserLeftEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLeftEvent.ProtoReflect.Descriptor instead.
func (*UserLeftEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{3}
}

func (x *UserLeftEvent) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *UserLeftEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserLeftEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UserSpeakingEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Speaking      bool                   `protobuf:"varint,3,opt,name=speaking,proto3" json:"speaking,omitempty"` // true when speaking starts, false when stops
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSpeakingEvent) Reset() {
	*x = UserSpeakingEvent{}
	mi := &file_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSpeakingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSpeakingEvent) ProtoMessage() {}

func (x *UserSpeakingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSpeakingEvent.ProtoReflect.Descriptor instead.
func (*UserSpeakingEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{4}
}

func (x *UserSpeakingEvent) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *UserSpeakingEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserSpeakingEvent) GetSpeaking() bool {
	if x != nil {
		return x.Speaking
	}
	return false
}

type ChannelCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentId      string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	MaxClients    int32                  `protobuf:"varint,4,opt,name=max_clients,json=maxClients,proto3" json:"max_clients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelCreatedEvent) Reset() {
	*x = ChannelCreatedEvent{}
	mi := &file_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelCreatedEvent) ProtoMessage() {}

func (x *ChannelCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelCreatedEvent.ProtoReflect.Descriptor instead.
func (*ChannelCreatedEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{5}
}

func (x *ChannelCreatedEvent) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ChannelCreatedEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChannelCreatedEvent) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *ChannelCreatedEvent) GetMaxClients() int32 {
	if x != nil {
		return x.MaxClients
	}
	return 0
}

type ChannelDeletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelDeletedEvent) Reset() {
	*x = ChannelDeletedEvent{}
	mi := &file_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelDeletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelDeletedEvent) ProtoMessage() {}

func (x *ChannelDeletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelDeletedEvent.ProtoReflect.Descriptor instead.
func (*ChannelDeletedEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{6}
}

func (x *ChannelDeletedEvent) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ChannelDeletedEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UserMovedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FromChannelId string                 `protobuf:"bytes,2,opt,name=from_channel_id,json=fromChannelId,proto3" json:"from_channel_id,omitempty"`
	ToChannelId   string                 `protobuf:"bytes,3,opt,name=to_channel_id,json=toChannelId,proto3" json:"to_channel_id,omitempty"`
	MovedBy       string                 `protobuf:"bytes,4,opt,name=moved_by,json=movedBy,proto3" json:"moved_by,omitempty"` // user id of the actor
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMovedEvent) Reset() {
	*x = UserMovedEvent{}
	mi := &file_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMovedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMovedEvent) ProtoMessage() {}

func (x *UserMovedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMovedEvent.ProtoReflect.Descriptor instead.
func (*UserMovedEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{7}
}

func (x *UserMovedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserMovedEvent) GetFromChannelId() string {
	if x != nil {
		return x.FromChannelId
	}
	return ""
}

func (x *UserMovedEvent) GetToChannelId() string {
	if x != nil {
		return x.ToChannelId
	}
	return ""
}

func (x *UserMovedEvent) GetMovedBy() string {
	if x != nil {
		return x.MovedBy
	}
	return ""
}

type UserKickedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	KickedBy      string                 `protobuf:"bytes,3,opt,name=kicked_by,json=kickedBy,proto3" json:"kicked_by,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserKickedEvent) Reset() {
	*x = UserKickedEvent{}
	mi := &file_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserKickedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserKickedEvent) ProtoMessage() {}

func (x *UserKickedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserKickedEvent.ProtoReflect.Descriptor instead.
func (*UserKickedEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{8}
}

func (x *UserKickedEvent) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *UserKickedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserKickedEvent) GetKickedBy() string {
	if x != nil {
		return x.KickedBy
	}
	return ""
}

func (x *UserKickedEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UserBannedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BannedBy      string                 `protobuf:"bytes,2,opt,name=banned_by,json=bannedBy,proto3" json:"banned_by,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // unix millis; 0 means permanent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBannedEvent) Reset() {
	*x = UserBannedEvent{}
	mi := &file_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBannedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBannedEvent) ProtoMessage() {}

func (x *UserBannedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBannedEvent.ProtoReflect.Descriptor instead.
func (*UserBannedEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{9}
}

func (x *UserBannedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserBannedEvent) GetBannedBy() string {
	if x != nil {
		return x.BannedBy
	}
	return ""
}

func (x *UserBannedEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *UserBannedEvent) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

var File_events_proto protoreflect.FileDescriptor

const file_events_proto_rawDesc = "" +
	"\n" +
	"\fevents.proto\x12\bvoicx.v1\"N\n" +
	"\x16SubscribeEventsRequest\x124\n" +
	"\vevent_types\x18\x01 \x03(\x0e2\x13.voicx.v1.EventTypeR\n" +
	"eventTypes\"\xee\x04\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.voicx.v1.EventTypeR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12<\n" +
	"\vuser_joined\x18\n" +
	" \x01(\v2\x19.voicx.v1.UserJoinedEventH\x00R\n" +
	"userJoined\x126\n" +
	"\tuser_left\x18\v \x01(\v2\x17.voicx.v1.UserLeftEventH\x00R\buserLeft\x12B\n" +
	"\ruser_speaking\x18\f \x01(\v2\x1b.voicx.v1.UserSpeakingEventH\x00R\fuserSpeaking\x12H\n" +
	"\x0fchannel_created\x18\r \x01(\v2\x1d.voicx.v1.ChannelCreatedEventH\x00R\x0echannelCreated\x12H\n" +
	"\x0fchannel_deleted\x18\x0e \x01(\v2\x1d.voicx.v1.ChannelDeletedEventH\x00R\x0echannelDeleted\x129\n" +
	"\n" +
	"user_moved\x18\x0f \x01(\v2\x18.voicx.v1.UserMovedEventH\x00R\tuserMoved\x12<\n" +
	"\vuser_kicked\x18\x10 \x01(\v2\x19.voicx.v1.UserKickedEventH\x00R\n" +
	"userKicked\x12<\n" +
	"\vuser_banned\x18\x11 \x01(\v2\x19.voicx.v1.UserBannedEventH\x00R\n" +
	"userBannedB\t\n" +
	"\apayload\"l\n" +
	"\x0fUserJoinedEvent\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\"_\n" +
	"\rUserLeftEvent\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"g\n" +
	"\x11UserSpeakingEvent\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\bspeaking\x18\x03 \x01(\bR\bspeaking\"\x86\x01\n" +
	"\x13ChannelCreatedEvent\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\x12\x1f\n" +
	"\vmax_clients\x18\x04 \x01(\x05R\n" +
	"maxClients\"L\n" +
	"\x13ChannelDeletedEvent\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x90\x01\n" +
	"\x0eUserMovedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12&\n" +
	"\x0ffrom_channel_id\x18\x02 \x01(\tR\rfromChannelId\x12\"\n" +
	"\rto_channel_id\x18\x03 \x01(\tR\vtoChannelId\x12\x19\n" +
	"\bmoved_by\x18\x04 \x01(\tR\amovedBy\"~\n" +
	"\x0fUserKickedEvent\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tkicked_by\x18\x03 \x01(\tR\bkickedBy\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"~\n" +
	"\x0fUserBannedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tbanned_by\x18\x02 \x01(\tR\bbannedBy\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt*\x8e\x02\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16EVENT_TYPE_USER_JOINED\x10\x01\x12\x18\n" +
	"\x14EVENT_TYPE_USER_LEFT\x10\x02\x12\x1c\n" +
	"\x18EVENT_TYPE_USER_SPEAKING\x10\x03\x12\x1e\n" +
	"\x1aEVENT_TYPE_CHANNEL_CREATED\x10\x04\x12\x1e\n" +
	"\x1aEVENT_TYPE_CHANNEL_DELETED\x10\x05\x12\x19\n" +
	"\x15EVENT_TYPE_USER_MOVED\x10\x06\x12\x1a\n" +
	"\x16EVENT_TYPE_USER_KICKED\x10\a\x12\x1a\n" +
	"\x16EVENT_TYPE_USER_BANNED\x10\b2J\n" +
	"\x06Events\x12@\n" +
	"\tSubscribe\x12 .voicx.v1.SubscribeEventsRequest\x1a\x0f.voicx.v1.Event0\x01B\x12Z\x10voicx/v1;voicxv1b\x06proto3"

var (
	file_events_proto_rawDescOnce sync.Once
	file_events_proto_rawDescData []byte
)

func file_events_proto_rawDescGZIP() []byte {
	file_events_proto_rawDescOnce.Do(func() {
		file_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)))
	})
	return file_events_proto_rawDescData
}

var file_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_events_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_events_proto_goTypes = []any{
	(EventType)(0),                 // 0: voicx.v1.EventType
	(*SubscribeEventsRequest)(nil), // 1: voicx.v1.SubscribeEventsRequest
	(*Event)(nil),                  // 2: voicx.v1.Event
	(*UserJoinedEvent)(nil),        // 3: voicx.v1.UserJoinedEvent
	(*UserLeftEvent)(nil),          // 4: voicx.v1.UserLeftEvent
	(*UserSpeakingEvent)(nil),      // 5: voicx.v1.UserSpeakingEvent
	(*ChannelCreatedEvent)(nil),    // 6: voicx.v1.ChannelCreatedEvent
	(*ChannelDeletedEvent)(nil),    // 7: voicx.v1.ChannelDeletedEvent
	(*UserMovedEvent)(nil),         // 8: voicx.v1.UserMovedEvent
	(*UserKickedEvent)(nil),        // 9: voicx.v1.UserKickedEvent
	(*UserBannedEvent)(nil),        // 10: voicx.v1.UserBannedEvent
}
var file_events_proto_depIdxs = []int32{
	0,  // 0: voicx.v1.SubscribeEventsRequest.event_types:type_name -> voicx.v1.EventType
	0,  // 1: voicx.v1.Event.type:type_name -> voicx.v1.EventType
	3,  // 2: voicx.v1.Event.user_joined:type_name -> voicx.v1.UserJoinedEvent
	4,  // 3: voicx.v1.Event.user_left:type_name -> voicx.v1.UserLeftEvent
	5,  // 4: voicx.v1.Event.user_speaking:type_name -> voicx.v1.UserSpeakingEvent
	6,  // 5: voicx.v1.Event.channel_created:type_name -> voicx.v1.ChannelCreatedEvent
	7,  // 6: voicx.v1.Event.channel_deleted:type_name -> voicx.v1.ChannelDeletedEvent
	8,  // 7: voicx.v1.Event.user_moved:type_name -> voicx.v1.UserMovedEvent
	9,  // 8: voicx.v1.Event.user_kicked:type_name -> voicx.v1.UserKickedEvent
	10, // 9: voicx.v1.Event.user_banned:type_name -> voicx.v1.UserBannedEvent
	1,  // 10: voicx.v1.Events.Subscribe:input_type -> voicx.v1.SubscribeEventsRequest
	2,  // 11: voicx.v1.Events.Subscribe:output_type -> voicx.v1.Event
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_events_proto_init() }
func file_events_proto_init() {
	if File_events_proto != nil {
		return
	}
	file_events_proto_msgTypes[1].OneofWrappers = []any{
		(*Event_UserJoined)(nil),
		(*Event_UserLeft)(nil),
		(*Event_UserSpeaking)(nil),
		(*Event_ChannelCreated)(nil),
		(*Event_ChannelDeleted)(nil),
		(*Event_UserMoved)(nil),
		(*Event_UserKicked)(nil),
		(*Event_UserBanned)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_events_proto_goTypes,
		DependencyIndexes: file_events_proto_depIdxs,
		EnumInfos:         file_events_proto_enumTypes,
		MessageInfos:      file_events_proto_msgTypes,
	}.Build()
	File_events_proto = out.File
	file_events_proto_goTypes = nil
	file_events_proto_depIdxs = nil
}
