// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: signaling.proto

package voicxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SignalMessage is the envelope for all signaling payloads exchanged over the
// signaling stream. Exactly one payload field should be set per message.
type SignalMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ClientId  string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ChannelId string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SignalMessage_JoinChannel
	//	*SignalMessage_LeaveChannel
	//	*SignalMessage_Subscribe
	//	*SignalMessage_Unsubscribe
	//	*SignalMessage_SdpOffer
	//	*SignalMessage_SdpAnswer
	//	*SignalMessage_IceCandidate
	//	*SignalMessage_Bye
	Payload       isSignalMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalMessage) Reset() {
	*x = SignalMessage{}
	mi := &file_signaling_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalMessage) ProtoMessage() {}

func (x *SignalMessage) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalMessage.ProtoReflect.Descriptor instead.
func (*SignalMessage) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{0}
}

func (x *SignalMessage) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SignalMessage) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *SignalMessage) GetPayload() isSignalMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SignalMessage) GetJoinChannel() *JoinChannel {
	if x != nil {
		if x, ok := x.Payload.(*SignalMessage_JoinChannel); ok {
			return x.JoinChannel
		}
	}
	return nil
}

func (x *SignalMessage) GetLeaveChannel() *LeaveChannel {
	if x != nil {
		if x, ok := x.Payload.(*SignalMessage_LeaveChannel); ok {
			return x.LeaveChannel
		}
	}
	return nil
}

func (x *SignalMessage) GetSubscribe() *Subscribe {
	if x != nil {
		if x, ok := x.Payload.(*SignalMessage_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *SignalMessage) GetUnsubscribe() *Unsubscribe {
	if x != nil {
		if x, ok := x.Payload.(*SignalMessage_Unsubscribe); ok {
			return x.Unsubscribe
		}
	}
	return nil
}

func (x *SignalMessage) GetSdpOffer() *SdpOffer {
	if x != nil {
		if x, ok := x.Payload.(*SignalMessage_SdpOffer); ok {
			return x.SdpOffer
		}
	}
	return nil
}

func (x *SignalMessage) GetSdpAnswer() *SdpAnswer {
	if x != nil {
		if x, ok := x.Payload.(*SignalMessage_SdpAnswer); ok {
			return x.SdpAnswer
		}
	}
	return nil
}

func (x *SignalMessage) GetIceCandidate() *IceCandidate {
	if x != nil {
		if x, ok := x.Payload.(*SignalMessage_IceCandidate); ok {
			return x.IceCandidate
		}
	}
	return nil
}

func (x *SignalMessage) GetBye() *Bye {
	if x != nil {
		if x, ok := x.Payload.(*SignalMessage_Bye); ok {
			return x.Bye
		}
	}
	return nil
}

type isSignalMessage_Payload interface {
	isSignalMessage_Payload()
}

type SignalMessage_JoinChannel struct {
	JoinChannel *JoinChannel `protobuf:"bytes,10,opt,name=join_channel,json=joinChannel,proto3,oneof"`
}

type SignalMessage_LeaveChannel struct {
	LeaveChannel *LeaveChannel `protobuf:"bytes,11,opt,name=leave_channel,json=leaveChannel,proto3,oneof"`
}

type SignalMessage_Subscribe struct {
	Subscribe *Subscribe `protobuf:"bytes,12,opt,name=subscribe,proto3,oneof"`
}

type SignalMessage_Unsubscribe struct {
	Unsubscribe *Unsubscribe `protobuf:"bytes,13,opt,name=unsubscribe,proto3,oneof"`
}

type SignalMessage_SdpOffer struct {
	SdpOffer *SdpOffer `protobuf:"bytes,14,opt,name=sdp_offer,json=sdpOffer,proto3,oneof"`
}

type SignalMessage_SdpAnswer struct {
	SdpAnswer *SdpAnswer `protobuf:"bytes,15,opt,name=sdp_answer,json=sdpAnswer,proto3,oneof"`
}

type SignalMessage_IceCandidate struct {
	IceCandidate *IceCandidate `protobuf:"bytes,16,opt,name=ice_candidate,json=iceCandidate,proto3,oneof"`
}

type SignalMessage_Bye struct {
	Bye *Bye `protobuf:"bytes,17,opt,name=bye,proto3,oneof"`
}

func (*SignalMessage_JoinChannel) isSignalMessage_Payload() {}

func (*SignalMessage_LeaveChannel) isSignalMessage_Payload() {}

func (*SignalMessage_Subscribe) isSignalMessage_Payload() {}

func (*SignalMessage_Unsubscribe) isSignalMessage_Payload() {}

func (*SignalMessage_SdpOffer) isSignalMessage_Payload() {}

func (*SignalMessage_SdpAnswer) isSignalMessage_Payload() {}

func (*SignalMessage_IceCandidate) isSignalMessage_Payload() {}

func (*SignalMessage_Bye) isSignalMessage_Payload() {}

// JoinChannel requests membership in a channel for media exchange.
type JoinChannel struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ChannelId string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// Capabilities advertised by the client (e.g. "opus", "vp8", "h264").
	Capabilities []string `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// True if the client intends to publish media; false for subscribe-only.
	Publish       bool `protobuf:"varint,3,opt,name=publish,proto3" json:"publish,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinChannel) Reset() {
	*x = JoinChannel{}
	mi := &file_signaling_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinChannel) ProtoMessage() {}

func (x *JoinChannel) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinChannel.ProtoReflect.Descriptor instead.
func (*JoinChannel) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{1}
}

func (x *JoinChannel) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *JoinChannel) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *JoinChannel) GetPublish() bool {
	if x != nil {
		return x.Publish
	}
	return false
}

// LeaveChannel relinquishes membership in a channel.
type LeaveChannel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveChannel) Reset() {
	*x = LeaveChannel{}
	mi := &file_signaling_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveChannel) ProtoMessage() {}

func (x *LeaveChannel) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveChannel.ProtoReflect.Descriptor instead.
func (*LeaveChannel) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{2}
}

func (x *LeaveChannel) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *LeaveChannel) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Subscribe requests the server to forward media from a publisher.
type Subscribe struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ChannelId string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// Publisher to subscribe to; empty means all publishers in the channel.
	PublisherId   string   `protobuf:"bytes,2,opt,name=publisher_id,json=publisherId,proto3" json:"publisher_id,omitempty"`
	MediaTypes    []string `protobuf:"bytes,3,rep,name=media_types,json=mediaTypes,proto3" json:"media_types,omitempty"` // e.g. ["audio", "video"]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscribe) Reset() {
	*x = Subscribe{}
	mi := &file_signaling_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribe) ProtoMessage() {}

func (x *Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribe.ProtoReflect.Descriptor instead.
func (*Subscribe) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{3}
}

func (x *Subscribe) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *Subscribe) GetPublisherId() string {
	if x != nil {
		return x.PublisherId
	}
	return ""
}

func (x *Subscribe) GetMediaTypes() []string {
	if x != nil {
		return x.MediaTypes
	}
	return nil
}

// Unsubscribe stops a previously established subscription.
type Unsubscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	PublisherId   string                 `protobuf:"bytes,2,opt,name=publisher_id,json=publisherId,proto3" json:"publisher_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unsubscribe) Reset() {
	*x = Unsubscribe{}
	mi := &file_signaling_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unsubscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unsubscribe) ProtoMessage() {}

func (x *Unsubscribe) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unsubscribe.ProtoReflect.Descriptor instead.
func (*Unsubscribe) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{4}
}

func (x *Unsubscribe) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *Unsubscribe) GetPublisherId() string {
	if x != nil {
		return x.PublisherId
	}
	return ""
}

// SdpOffer carries an SDP offer, typically from a client to the server.
type SdpOffer struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ChannelId   string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	PublisherId string                 `protobuf:"bytes,2,opt,name=publisher_id,json=publisherId,proto3" json:"publisher_id,omitempty"`
	Sdp         string                 `protobuf:"bytes,3,opt,name=sdp,proto3" json:"sdp,omitempty"`
	// Type of session: "publish" or "subscribe".
	SessionType   string `protobuf:"bytes,4,opt,name=session_type,json=sessionType,proto3" json:"session_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SdpOffer) Reset() {
	*x = SdpOffer{}
	mi := &file_signaling_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SdpOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SdpOffer) ProtoMessage() {}

func (x *SdpOffer) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SdpOffer.ProtoReflect.Descriptor instead.
func (*SdpOffer) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{5}
}

func (x *SdpOffer) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *SdpOffer) GetPublisherId() string {
	if x != nil {
		return x.PublisherId
	}
	return ""
}

func (x *SdpOffer) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

func (x *SdpOffer) GetSessionType() string {
	if x != nil {
		return x.SessionType
	}
	return ""
}

// SdpAnswer carries an SDP answer, typically from the server to a client.
type SdpAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	PublisherId   string                 `protobuf:"bytes,2,opt,name=publisher_id,json=publisherId,proto3" json:"publisher_id,omitempty"`
	SubscriberId  string                 `protobuf:"bytes,3,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	Sdp           string                 `protobuf:"bytes,4,opt,name=sdp,proto3" json:"sdp,omitempty"`
	SessionType   string                 `protobuf:"bytes,5,opt,name=session_type,json=sessionType,proto3" json:"session_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SdpAnswer) Reset() {
	*x = SdpAnswer{}
	mi := &file_signaling_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SdpAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SdpAnswer) ProtoMessage() {}

func (x *SdpAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SdpAnswer.ProtoReflect.Descriptor instead.
func (*SdpAnswer) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{6}
}

func (x *SdpAnswer) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *SdpAnswer) GetPublisherId() string {
	if x != nil {
		return x.PublisherId
	}
	return ""
}

func (x *SdpAnswer) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

func (x *SdpAnswer) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

func (x *SdpAnswer) GetSessionType() string {
	if x != nil {
		return x.SessionType
	}
	return ""
}

// IceCandidate carries a single ICE candidate for trickle ICE.
type IceCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	PublisherId   string                 `protobuf:"bytes,2,opt,name=publisher_id,json=publisherId,proto3" json:"publisher_id,omitempty"`
	SubscriberId  string                 `protobuf:"bytes,3,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	Candidate     string                 `protobuf:"bytes,4,opt,name=candidate,proto3" json:"candidate,omitempty"`
	SdpMid        string                 `protobuf:"bytes,5,opt,name=sdp_mid,json=sdpMid,proto3" json:"sdp_mid,omitempty"`
	SdpMlineIndex int32                  `protobuf:"varint,6,opt,name=sdp_mline_index,json=sdpMlineIndex,proto3" json:"sdp_mline_index,omitempty"`
	// Direction: "offer" or "answer".
	Direction     string `protobuf:"bytes,7,opt,name=direction,proto3" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IceCandidate) Reset() {
	*x = IceCandidate{}
	mi := &file_signaling_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IceCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IceCandidate) ProtoMessage() {}

func (x *IceCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IceCandidate.ProtoReflect.Descriptor instead.
func (*IceCandidate) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{7}
}

func (x *IceCandidate) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *IceCandidate) GetPublisherId() string {
	if x != nil {
		return x.PublisherId
	}
	return ""
}

func (x *IceCandidate) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

func (x *IceCandidate) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

func (x *IceCandidate) GetSdpMid() string {
	if x != nil {
		return x.SdpMid
	}
	return ""
}

func (x *IceCandidate) GetSdpMlineIndex() int32 {
	if x != nil {
		return x.SdpMlineIndex
	}
	return 0
}

func (x *IceCandidate) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

// Bye signals graceful teardown of the signaling stream.
type Bye struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bye) Reset() {
	*x = Bye{}
	mi := &file_signaling_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bye) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bye) ProtoMessage() {}

func (x *Bye) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bye.ProtoReflect.Descriptor instead.
func (*Bye) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{8}
}

func (x *Bye) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_signaling_proto protoreflect.FileDescriptor

const file_signaling_proto_rawDesc = "" +
	"\n" +
	"\x0fsignaling.proto\x12\bvoicx.v1\"\x8c\x04\n" +
	"\rSignalMessage\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12:\n" +
	"\fjoin_channel\x18\n" +
	" \x01(\v2\x15.voicx.v1.JoinChannelH\x00R\vjoinChannel\x12=\n" +
	"\rleave_channel\x18\v \x01(\v2\x16.voicx.v1.LeaveChannelH\x00R\fleaveChannel\x123\n" +
	"\tsubscribe\x18\f \x01(\v2\x13.voicx.v1.SubscribeH\x00R\tsubscribe\x129\n" +
	"\vunsubscribe\x18\r \x01(\v2\x15.voicx.v1.UnsubscribeH\x00R\vunsubscribe\x121\n" +
	"\tsdp_offer\x18\x0e \x01(\v2\x12.voicx.v1.SdpOfferH\x00R\bsdpOffer\x124\n" +
	"\n" +
	"sdp_answer\x18\x0f \x01(\v2\x13.voicx.v1.SdpAnswerH\x00R\tsdpAnswer\x12=\n" +
	"\rice_candidate\x18\x10 \x01(\v2\x16.voicx.v1.IceCandidateH\x00R\ficeCandidate\x12!\n" +
	"\x03bye\x18\x11 \x01(\v2\r.voicx.v1.ByeH\x00R\x03byeB\t\n" +
	"\apayload\"j\n" +
	"\vJoinChannel\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\x12\x18\n" +
	"\apublish\x18\x03 \x01(\bR\apublish\"E\n" +
	"\fLeaveChannel\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"n\n" +
	"\tSubscribe\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12!\n" +
	"\fpublisher_id\x18\x02 \x01(\tR\vpublisherId\x12\x1f\n" +
	"\vmedia_types\x18\x03 \x03(\tR\n" +
	"mediaTypes\"O\n" +
	"\vUnsubscribe\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12!\n" +
	"\fpublisher_id\x18\x02 \x01(\tR\vpublisherId\"\x81\x01\n" +
	"\bSdpOffer\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12!\n" +
	"\fpublisher_id\x18\x02 \x01(\tR\vpublisherId\x12\x10\n" +
	"\x03sdp\x18\x03 \x01(\tR\x03sdp\x12!\n" +
	"\fsession_type\x18\x04 \x01(\tR\vsessionType\"\xa7\x01\n" +
	"\tSdpAnswer\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12!\n" +
	"\fpublisher_id\x18\x02 \x01(\tR\vpublisherId\x12#\n" +
	"\rsubscriber_id\x18\x03 \x01(\tR\fsubscriberId\x12\x10\n" +
	"\x03sdp\x18\x04 \x01(\tR\x03sdp\x12!\n" +
	"\fsession_type\x18\x05 \x01(\tR\vsessionType\"\xf2\x01\n" +
	"\fIceCandidate\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12!\n" +
	"\fpublisher_id\x18\x02 \x01(\tR\vpublisherId\x12#\n" +
	"\rsubscriber_id\x18\x03 \x01(\tR\fsubscriberId\x12\x1c\n" +
	"\tcandidate\x18\x04 \x01(\tR\tcandidate\x12\x17\n" +
	"\asdp_mid\x18\x05 \x01(\tR\x06sdpMid\x12&\n" +
	"\x0fsdp_mline_index\x18\x06 \x01(\x05R\rsdpMlineIndex\x12\x1c\n" +
	"\tdirection\x18\a \x01(\tR\tdirection\"\x1d\n" +
	"\x03Bye\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason2K\n" +
	"\tSignaling\x12>\n" +
	"\x06Signal\x12\x17.voicx.v1.SignalMessage\x1a\x17.voicx.v1.SignalMessage(\x010\x01B\x12Z\x10voicx/v1;voicxv1b\x06proto3"

var (
	file_signaling_proto_rawDescOnce sync.Once
	file_signaling_proto_rawDescData []byte
)

func file_signaling_proto_rawDescGZIP() []byte {
	file_signaling_proto_rawDescOnce.Do(func() {
		file_signaling_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_signaling_proto_rawDesc), len(file_signaling_proto_rawDesc)))
	})
	return file_signaling_proto_rawDescData
}

var file_signaling_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_signaling_proto_goTypes = []any{
	(*SignalMessage)(nil), // 0: voicx.v1.SignalMessage
	(*JoinChannel)(nil),   // 1: voicx.v1.JoinChannel
	(*LeaveChannel)(nil),  // 2: voicx.v1.LeaveChannel
	(*Subscribe)(nil),     // 3: voicx.v1.Subscribe
	(*Unsubscribe)(nil),   // 4: voicx.v1.Unsubscribe
	(*SdpOffer)(nil),      // 5: voicx.v1.SdpOffer
	(*SdpAnswer)(nil),     // 6: voicx.v1.SdpAnswer
	(*IceCandidate)(nil),  // 7: voicx.v1.IceCandidate
	(*Bye)(nil),           // 8: voicx.v1.Bye
}
var file_signaling_proto_depIdxs = []int32{
	1, // 0: voicx.v1.SignalMessage.join_channel:type_name -> voicx.v1.JoinChannel
	2, // 1: voicx.v1.SignalMessage.leave_channel:type_name -> voicx.v1.LeaveChannel
	3, // 2: voicx.v1.SignalMessage.subscribe:type_name -> voicx.v1.Subscribe
	4, // 3: voicx.v1.SignalMessage.unsubscribe:type_name -> voicx.v1.Unsubscribe
	5, // 4: voicx.v1.SignalMessage.sdp_offer:type_name -> voicx.v1.SdpOffer
	6, // 5: voicx.v1.SignalMessage.sdp_answer:type_name -> voicx.v1.SdpAnswer
	7, // 6: voicx.v1.SignalMessage.ice_candidate:type_name -> voicx.v1.IceCandidate
	8, // 7: voicx.v1.SignalMessage.bye:type_name -> voicx.v1.Bye
	0, // 8: voicx.v1.Signaling.Signal:input_type -> voicx.v1.SignalMessage
	0, // 9: voicx.v1.Signaling.Signal:output_type -> voicx.v1.SignalMessage
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_signaling_proto_init() }
func file_signaling_proto_init() {
	if File_signaling_proto != nil {
		return
	}
	file_signaling_proto_msgTypes[0].OneofWrappers = []any{
		(*SignalMessage_JoinChannel)(nil),
		(*SignalMessage_LeaveChannel)(nil),
		(*SignalMessage_Subscribe)(nil),
		(*SignalMessage_Unsubscribe)(nil),
		(*SignalMessage_SdpOffer)(nil),
		(*SignalMessage_SdpAnswer)(nil),
		(*SignalMessage_IceCandidate)(nil),
		(*SignalMessage_Bye)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_signaling_proto_rawDesc), len(file_signaling_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_signaling_proto_goTypes,
		DependencyIndexes: file_signaling_proto_depIdxs,
		MessageInfos:      file_signaling_proto_msgTypes,
	}.Build()
	File_signaling_proto = out.File
	file_signaling_proto_goTypes = nil
	file_signaling_proto_depIdxs = nil
}
