version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - bodyclose
    - copyloopvar
    - gocritic
    - govet
    - ineffassign
    - staticcheck
    - noctx
    - unused
